- type: roleLoadout
  id: SunriseJobHeadOfSecurity
  groups:
  - SunriseHeadofSecurityHead
  - SunriseHeadofSecurityNeck
  - SunriseHeadofSecurityJumpsuit
#  - SecurityBackpack
  - SunriseSecurityBackpack
  - SecurityBelt
  - SunriseHeadofSecurityOuterClothing
  - SecurityShoes
  - SunriseSurvivalSecurity
  - SunriseTrinkets
  - HeadofSecurityJobTrinkets
  - SunriseGroupSpeciesBreathToolSecurity
  - SecurityTrinkets
  - SunriseSecurityGunHos
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobWarden
  groups:
  - SunriseWardenHead
#  - WardenJumpsuit
#  - SecurityBackpack
  - SunriseWardenJumpsuit
  - SunriseSecurityBackpack
  - SecurityBelt
  - SunriseWardenOuterClothing
  - SecurityShoes
  - SunriseSurvivalSecurity
  - SunriseTrinkets
  - WardenJobTrinkets
  - SunriseGroupSpeciesBreathToolSecurity
  - SecurityTrinkets
  - SunriseWardenGun
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobSecurityOfficer
  groups:
  # - SecurityHead
  # - SecurityJumpsuit
  # - SecurityBackpack
  - SunriseSecurityHead
  - SunriseSecurityJumpsuit
  - SunriseSecurityBackpack
  - SecurityGlasses
  - SecurityOuterClothing
  - SecurityShoes
  - SecurityPDA
  - SecurityBelt
  - SunriseSurvivalSecurity
  - SunriseTrinkets
  - SecurityJobTrinkets
  - SunriseGroupSpeciesBreathToolSecurity
  - SecurityTrinkets
  - SunriseSecurityGun
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobDetective
  groups:
  - DetectiveHead
  - SunriseDetectiveNeck
  - DetectiveJumpsuit
#  - SecurityBackpack
  - SunriseSecurityBackpack
  - SunriseDetectiveOuterClothing
  - SecurityShoes
  - SunriseSurvivalSecurity
  - SunriseTrinkets
  - DetectiveJobTrinkets
  - SunriseGroupSpeciesBreathToolSecurity
  - SecurityTrinkets
  - SunriseWeaponDetective
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobSecurityCadet
  groups:
#  - SecurityCadetJumpsuit
  - SunriseSecurityCadetJumpsuit
#  - SecurityBackpack
  - SunriseSecurityBackpack
  - SunriseSurvivalSecurity
  - SunriseTrinkets
  - SecurityCadetJobTrinkets
  - SunriseGroupSpeciesBreathToolSecurity
  - SecurityTrinkets
  - SunriseWeaponCadet
  - Bra
  - Pants
  - Socks
  - Contributors
