using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.AntagObjectives;

[GenerateTypedNameReferences]
public sealed partial class AntagObjectivesWindow : DefaultWindow
{
    public AntagObjectivesWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
