- type: entity
  id: BaseMechWeaponRange
  parent: BaseMechEquipment
  abstract: true
  components:
  - type: Battery
    maxCharge: 500 # Battery is charged by mech
    startingCharge: 500
  - type: Appearance
  - type: StaticPrice
    price: 1
  - type: Item
    size: Ginormous
  - type: MultiHandedItem
  - type: ClothingSpeedModifier
    walkModifier: 0.5
    sprintModifier: 0.5
  - type: HeldSpeedModifier