using Content.Client.Audio;
using Content.Client._Sunrise.Options.UI;
using Content.Shared._Sunrise.Lobby;
using Content.Shared._Sunrise.SunriseCCVars;
using Content.Shared.GameTicking;
using Content.Shared.GameTicking.Prototypes;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ExtraTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private SunriseOptionDropDownCVar<string> _lobbyBackgroundTypeOption = default!;
    private SunriseOptionDropDownCVar<string> _lobbyArtOption = default!;
    private SunriseOptionDropDownCVar<string> _lobbyAnimationOption = default!;
    private SunriseOptionDropDownCVar<string> _lobbyParallaxOption = default!;

    public ExtraTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionPercentSlider(
            SunriseCCVars.TTSVolume,
            SliderTts,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionPercentSlider(
            SunriseCCVars.TTSRadioVolume,
            SliderTtsRadio,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionCheckBox(SunriseCCVars.TTSClientEnabled, TtsClientCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.TTSClientQueueEnabled, TtsClientCheckBoxQueue);
        Control.AddOptionCheckBox(SunriseCCVars.TTSRadioGhostEnabled, TtsRadioGhostCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.TapePlayerClientEnabled, TapePlayerClientCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.JumpSoundDisable, JumpSoundDisableCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.VoteMusicDisable, VoteMusicDisableCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.MuteGhostRoleNotification, MuteGhostRoleNotificationCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.TracesEnabled, TracesCheckBox);

        Control.AddOptionCheckBox(SunriseCCVars.PlayHeartBeatSound, PlayHeartbeatSound);

        _lobbyBackgroundTypeOption = Control.AddOption(new SunriseOptionDropDownCVar<string>(
            Control,
            _cfg,
            SunriseCCVars.LobbyBackgroundType,
            DropDownLobbyBackgroundType,
            BuildLobbyBackgroundTypeOptions()));
        _lobbyArtOption = Control.AddOption(new SunriseOptionDropDownCVar<string>(
            Control,
            _cfg,
            SunriseCCVars.LobbyArt,
            DropDownLobbyArt,
            BuildLobbyArtOptions()));
        _lobbyAnimationOption = Control.AddOption(new SunriseOptionDropDownCVar<string>(
            Control,
            _cfg,
            SunriseCCVars.LobbyAnimation,
            DropDownLobbyAnimation,
            BuildLobbyAnimationOptions()));
        _lobbyParallaxOption = Control.AddOption(new SunriseOptionDropDownCVar<string>(
            Control,
            _cfg,
            SunriseCCVars.LobbyParallax,
            DropDownLobbyParallax,
            BuildLobbyParallaxOptions()));

        _cfg.OnValueChanged(SunriseCCVars.LobbyBackgroundType, OnLobbyBackgroundTypeChanged, true);
        _cfg.OnValueChanged(SunriseCCVars.LobbyBackgroundPreset, OnLobbyBackgroundPresetChanged, true);

        Control.AddOptionPercentSlider(SunriseCCVars.LobbyOpacity, LobbyOpacitySlider);
        Control.AddOptionCheckBox(SunriseCCVars.LobbyUnloadResources, LobbyUnloadResourcesCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.DamageOverlayEnable, DamageOverlayEnableCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.DamageOverlaySelf, DamageOverlaySelfCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.DamageOverlayStructures, DamageOverlayStructuresCheckBox);

        Control.AddOptionCheckBox(SunriseCCVars.ChatIconsEnable, ChatIconsEnableCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.ChatPointingVisuals, ChatPointingVisualsEnableCheckBox);

        Control.Initialize();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _cfg.UnsubValueChanged(SunriseCCVars.LobbyBackgroundType, OnLobbyBackgroundTypeChanged);
        _cfg.UnsubValueChanged(SunriseCCVars.LobbyBackgroundPreset, OnLobbyBackgroundPresetChanged);
    }

    private void OnLobbyBackgroundPresetChanged(string presetId)
    {
        RefreshLobbyBackgroundOptions();
    }

    private void OnLobbyBackgroundTypeChanged(string lobbyBackgroundTypeString)
    {
        var allowedTypes = GetAllowedLobbyBackgroundTypes();
        if (lobbyBackgroundTypeString == "Random")
        {
            DropDownLobbyArt.Visible = allowedTypes.Contains(LobbyBackgroundType.Art);
            DropDownLobbyAnimation.Visible = allowedTypes.Contains(LobbyBackgroundType.Animation);
            DropDownLobbyParallax.Visible = allowedTypes.Contains(LobbyBackgroundType.Parallax);
            return;
        }

        var lobbyBackgroundType = ResolveAllowedLobbyBackgroundType(lobbyBackgroundTypeString, allowedTypes);
        DropDownLobbyArt.Visible = lobbyBackgroundType == LobbyBackgroundType.Art;
        DropDownLobbyAnimation.Visible = lobbyBackgroundType == LobbyBackgroundType.Animation;
        DropDownLobbyParallax.Visible = lobbyBackgroundType == LobbyBackgroundType.Parallax;
    }

    private void RefreshLobbyBackgroundOptions()
    {
        _lobbyBackgroundTypeOption.ReplaceOptions(BuildLobbyBackgroundTypeOptions());
        _lobbyArtOption.ReplaceOptions(BuildLobbyArtOptions());
        _lobbyAnimationOption.ReplaceOptions(BuildLobbyAnimationOptions());
        _lobbyParallaxOption.ReplaceOptions(BuildLobbyParallaxOptions());
        OnLobbyBackgroundTypeChanged(_cfg.GetCVar(SunriseCCVars.LobbyBackgroundType));
        Control.ValueChanged();
    }

    private LobbyBackgroundType ResolveAllowedLobbyBackgroundType(
        string configuredType,
        IReadOnlyList<LobbyBackgroundType> allowedTypes)
    {
        if (Enum.TryParse<LobbyBackgroundType>(configuredType, true, out var resolvedType) &&
            allowedTypes.Contains(resolvedType))
        {
            return resolvedType;
        }

        if (allowedTypes.Count > 0)
            return allowedTypes[0];

        return LobbyBackgroundType.Parallax;
    }

    private List<SunriseOptionDropDownCVar<string>.ValueOption> BuildLobbyBackgroundTypeOptions()
    {
        var options = new List<SunriseOptionDropDownCVar<string>.ValueOption>
        {
            new("Random", Loc.GetString("background-type-Random")),
        };

        foreach (var backgroundType in GetAllowedLobbyBackgroundTypes())
        {
            var label = Loc.GetString($"background-type-{backgroundType}");
            options.Add(new SunriseOptionDropDownCVar<string>.ValueOption(backgroundType.ToString(), label));
        }

        return options;
    }

    private List<SunriseOptionDropDownCVar<string>.ValueOption> BuildLobbyArtOptions()
    {
        var options = new List<SunriseOptionDropDownCVar<string>.ValueOption>
        {
            new("Random", Loc.GetString("lobby-art-Random")),
        };

        foreach (var lobbyArt in GetAllowedLobbyArts())
        {
            var label = Loc.GetString($"lobby-art-{lobbyArt.ID}");
            options.Add(new SunriseOptionDropDownCVar<string>.ValueOption(lobbyArt.ID, label));
        }

        return options;
    }

    private List<SunriseOptionDropDownCVar<string>.ValueOption> BuildLobbyAnimationOptions()
    {
        var options = new List<SunriseOptionDropDownCVar<string>.ValueOption>
        {
            new("Random", Loc.GetString("lobby-animation-Random")),
        };

        foreach (var lobbyAnimation in GetAllowedLobbyAnimations())
        {
            var label = Loc.GetString($"lobby-animation-{lobbyAnimation.ID}");
            options.Add(new SunriseOptionDropDownCVar<string>.ValueOption(lobbyAnimation.ID, label));
        }

        return options;
    }

    private List<SunriseOptionDropDownCVar<string>.ValueOption> BuildLobbyParallaxOptions()
    {
        var options = new List<SunriseOptionDropDownCVar<string>.ValueOption>
        {
            new("Random", Loc.GetString("lobby-parallax-Random")),
        };

        foreach (var lobbyParallax in GetAllowedLobbyParallaxes())
        {
            var label = Loc.GetString($"lobby-parallax-{lobbyParallax.ID}");
            options.Add(new SunriseOptionDropDownCVar<string>.ValueOption(lobbyParallax.ID, label));
        }

        return options;
    }

    private IReadOnlyList<LobbyBackgroundType> GetAllowedLobbyBackgroundTypes()
    {
        var availableTypes = new List<LobbyBackgroundType>();

        if (GetAllowedLobbyAnimations().Any())
            availableTypes.Add(LobbyBackgroundType.Animation);

        if (GetAllowedLobbyParallaxes().Any())
            availableTypes.Add(LobbyBackgroundType.Parallax);

        if (GetAllowedLobbyArts().Any())
            availableTypes.Add(LobbyBackgroundType.Art);

        if (availableTypes.Count > 0)
            return availableTypes;

        foreach (var backgroundType in Enum.GetValues<LobbyBackgroundType>())
        {
            availableTypes.Add(backgroundType);
        }

        return availableTypes;
    }

    private IEnumerable<LobbyArtPrototype> GetAllowedLobbyArts()
    {
        var preset = GetCurrentLobbyBackgroundPreset();
        return _prototypeManager.EnumeratePrototypes<LobbyArtPrototype>()
            .Where(x => preset == null || preset.AllArtsAllowed || preset.WhitelistArts.Contains(x.ID));
    }

    private IEnumerable<LobbyAnimationPrototype> GetAllowedLobbyAnimations()
    {
        var preset = GetCurrentLobbyBackgroundPreset();
        return _prototypeManager.EnumeratePrototypes<LobbyAnimationPrototype>()
            .Where(x => preset == null || preset.AllAnimationsAllowed || preset.WhitelistAnimations.Contains(x.ID));
    }

    private IEnumerable<LobbyParallaxPrototype> GetAllowedLobbyParallaxes()
    {
        var preset = GetCurrentLobbyBackgroundPreset();
        return _prototypeManager.EnumeratePrototypes<LobbyParallaxPrototype>()
            .Where(x => preset == null || preset.AllParallaxesAllowed || preset.WhitelistParallaxes.Contains(x.ID));
    }

    private LobbyBackgroundPresetPrototype? GetCurrentLobbyBackgroundPreset()
    {
        var presetId = _cfg.GetCVar(SunriseCCVars.LobbyBackgroundPreset);
        if (_prototypeManager.TryIndex<LobbyBackgroundPresetPrototype>(presetId, out var preset))
            return preset;

        return null;
    }
}
