using Content.Client.Resources;
using Content.Client._Sunrise.UserInterface.CustomControls;
using Content.Shared._Sunrise.Messenger;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.RichText;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Threading;
using System.Threading.Tasks;
using Content.Client._Sunrise.Messenger;

namespace Content.Client._Sunrise.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class SunriseBwoinkPanel : BoxContainer
    {
        [Dependency] private readonly IUserInterfaceManager _ui = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;

        private static readonly Type[] AllowedTags = new Type[]
        {
            typeof(CommandLinkTag),
            typeof(BoldItalicTag),
            typeof(BoldTag),
            typeof(BulletTag),
            typeof(ColorTag),
            typeof(HeadingTag),
            typeof(ItalicTag),
            typeof(EmojiTag)
        };

        private readonly Action<string> _messageSender;

        public int Unread { get; private set; } = 0;
        public event Action<string>? InputTextChanged;

        // Sunrise-Start
        public DateTime LastMessage { get; set; } = DateTime.MinValue;
        public bool LoadDb { get; set; }
        private DateTime _cooldownEnd = DateTime.MinValue;
        private CancellationTokenSource? _cooldownCancellationTokenSource;
        private Action? _emojiPickerCleanup;
        // Sunrise-End

        public SunriseBwoinkPanel(Action<string> messageSender)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _messageSender = messageSender;

            OnVisibilityChanged += c =>
            {
                if (c.Visible)
                    Unread = 0;
            };

            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;

            // Sunrise-Start
            AdminWhoButton.OnPressed += AdminWho_OnPressed;
            // Sunrise-End

            UpdateTypingIndicator();

            _emojiPickerCleanup = EmojiButtonHelper.SetupEmojiButton(EmojiButton, SenderLineEdit, _resourceCache);
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text))
                return;

            _messageSender(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        {
            InputTextChanged?.Invoke(args.Text);
        }

        // Sunrise-Start
        private void AdminWho_OnPressed(BaseButton.ButtonEventArgs args)
        {
            var ctrl = _ui.GetUIController<Client.Administration.UI.Bwoink.AdminWhoUIController>();
            ctrl.Toggle();
        }
        // Sunrise-End

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible && !message.DbLoad)
                Unread++;

            // Sunrise-Start
            if (LastMessage != DateTime.MinValue && LastMessage.Date != message.SentAt.Date)
            {
                var dateHeader = new FormattedMessage(1);
                dateHeader.AddMarkupOrThrow($"[center=\"{message.SentAt:dd.MM.yyyy}\"]");
                TextOutput.AddMessage(dateHeader, AllowedTags);
            }

            var text = message.Text;
            if (SharedEmojiSystem.IsContainsAnyEmoji(text))
            {
                var emoji = _entManager.System<EmojiSystem>();
                text = emoji.ParseEmojis(text);
            }
            // Sunrise-End

            var formatted = new FormattedMessage(1);
            var formattedTime = $"[bold]{message.SentAt:HH:mm}[/bold]";
            formatted.AddMarkupOrThrow($"{formattedTime} {text}");
            TextOutput.AddMessage(formatted, AllowedTags);
            if (!message.DbLoad)
                LastMessage = message.SentAt;
        }

        public void UpdatePlayerTyping(string playerName, bool typing)
        {
            TypingIndicator.Text = typing ? $"{playerName} is typing..." : string.Empty;
        }

        private void UpdateTypingIndicator()
        {
            TypingIndicator.Text = string.Empty;
        }

        // Sunrise-Start
        public void OnCooldownReceived(BwoinkCooldownMessage message)
        {
            _cooldownEnd = DateTime.UtcNow + message.RemainingCooldown;
            _cooldownCancellationTokenSource?.Cancel();
            _cooldownCancellationTokenSource = new CancellationTokenSource();

            var token = _cooldownCancellationTokenSource.Token;
            UpdateCooldownUI(token);
        }

        private async void UpdateCooldownUI(CancellationToken token)
        {
            SenderLineEdit.Editable = false;
            SenderLineEdit.PlaceHolder = Loc.GetString("bwoink-cooldown-placeholder", ("time", (int)Math.Max(0, (_cooldownEnd - DateTime.UtcNow).TotalSeconds)));

            while (DateTime.UtcNow < _cooldownEnd)
            {
                if (token.IsCancellationRequested)
                    return;

                SenderLineEdit.PlaceHolder = Loc.GetString("bwoink-cooldown-placeholder", ("time", (int)Math.Max(0, (_cooldownEnd - DateTime.UtcNow).TotalSeconds)));
                await Task.Delay(500, token);
            }

            SenderLineEdit.Editable = true;
            SenderLineEdit.PlaceHolder = Loc.GetString("bwoink-panel-placeholder");
        }
        // Sunrise-End

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            SenderLineEdit.OnTextEntered -= Input_OnTextEntered;
            SenderLineEdit.OnTextChanged -= Input_OnTextChanged;
            InputTextChanged = null;
            _cooldownCancellationTokenSource?.Cancel();
            _cooldownCancellationTokenSource = null;
            _emojiPickerCleanup?.Invoke();
        }
    }
}
