- type: roleLoadout
  id: SunriseJobHeadOfPersonnel
  groups:
  - GroupTankHarness
  - HoPHead
  - SunriseHoPNeck
  - HoPJumpsuit
  - HoPBackpack
  - HoPOuterClothing
  - SunriseHoPBra
  - SunriseHoPPants
  - SunriseGlasses
  - SunriseSurvival
  - SunriseTrinkets
  - HoPJobTrinkets
  - SunriseGroupSpeciesBreathTool
  - Socks
  - Contributors
