- type: roleLoadout
  id: SunriseJobQuartermaster
  groups:
  - GroupTankHarness
  - SunriseQuartermasterHead
  - SunriseQuartermasterMask
  - QuartermasterJumpsuit
  - SunriseQuartermasterGloves
  - CargoTechnicianBackpack
  - SunriseQuartermasterOuterClothing
  - SunriseQuartermasterNeck
  - SunriseQuartermasterShoes
  - SunriseGlasses
  - SunriseSurvival
  - SunriseTrinkets
  - QuartermasterJobTrinkets
  - SunriseGroupSpeciesBreathTool
  - TrinketsCargo
  - Bra
  - Pants
  - Socks
  - Contributors
