using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Sunrise.Tutorial.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.Tutorial.TutorialWindow;

[GenerateTypedNameReferences]
public sealed partial class TutorialWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    public Action<TutorialSequencePrototype>? OnTutorialButtonPressed;
    public Action? OnRequestCompletedTutorials;
    private TutorialCategoryButton? _selectedCategory;
    private readonly HashSet<string> _completedTutorials = new();
    private bool _completedTutorialsLoaded;

    public TutorialWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        OnOpen += () => OnRequestCompletedTutorials?.Invoke();
        GenerateCategories();
    }

    private void GenerateCategories()
    {
        var categories = _prototype.EnumeratePrototypes<TutorialCategoryPrototype>().ToList();

        categories.Sort((a, b)
            => string.Compare(Loc.GetString(a.Name), Loc.GetString(b.Name), StringComparison.CurrentCultureIgnoreCase));

        foreach (var category in categories)
        {
            var button = new TutorialCategoryButton(category, OnCategorySelected);
            CategoryContainer.AddChild(button);
        }

        // Select the first category by default
        if (CategoryContainer.ChildCount > 0 && CategoryContainer.Children[0] is TutorialCategoryButton firstCategory)
            OnCategorySelected(firstCategory);
    }

    private void OnCategorySelected(TutorialCategoryButton categoryButton)
    {
        _selectedCategory?.SetSelected(false);

        _selectedCategory = categoryButton;
        _selectedCategory.SetSelected(true);

        RebuildButtonsForCategory(_selectedCategory.Category);
    }

    private void PopulateButtonsForCategory(TutorialCategoryPrototype category)
    {
        foreach (var proto in TutorialPrototypeOrdering.GetOrderedTutorials(category, _prototype))
        {
            var status = Loc.GetString("tutorial-status-loading");
            if (_completedTutorialsLoaded)
            {
                var completed = _completedTutorials.Contains(proto.ID);
                status = completed ? Loc.GetString("tutorial-completed") : Loc.GetString("tutorial-is-not-completed");
            }

            var config = new TutorialWindowItemConfig
            {
                TitleText = proto.Name,
                Texture = proto.Texture,
                CropFocus = proto.CropFocus,
                DescriptionText = proto.Tooltip,
                StatusText = Loc.GetString("tutorial-status", ("status", status)),
                TimeText = Loc.GetString("tutorial-time", ("time", proto.Duration.ToString("mm\\:ss"))),
                StartText = Loc.GetString("tutorial-start"),
                OnStartPressed = () => OnTutorialButtonPressed?.Invoke(proto),
            };

            ButtonGrid.AddChild(new TutorialWindowItem(config));
        }
    }

    public void SetCompletedTutorials(IEnumerable<string> completedTutorials)
    {
        _completedTutorials.Clear();
        _completedTutorials.UnionWith(completedTutorials);
        _completedTutorialsLoaded = true;

        if (_selectedCategory != null)
            RebuildButtonsForCategory(_selectedCategory.Category);
    }
    private void RebuildButtonsForCategory(TutorialCategoryPrototype category)
    {
        ButtonGrid.DisposeAllChildren();
        UpdateCategoryProgress(category);
        PopulateButtonsForCategory(category);
    }

    private void UpdateCategoryProgress(TutorialCategoryPrototype category)
    {
        var tutorials = TutorialPrototypeOrdering.GetOrderedTutorials(category, _prototype);

        if (!_completedTutorialsLoaded)
        {
            CategoryProgressLabel.Text = Loc.GetString("tutorial-category-progress-loading");
            CategoryProgressBar.Value = 0;
            return;
        }

        var completedCount = 0;
        var completedDurationTicks = 0L;
        var totalDurationTicks = 0L;

        foreach (var tutorial in tutorials)
        {
            var durationTicks = tutorial.Duration.Ticks;
            totalDurationTicks += durationTicks;

            if (!_completedTutorials.Contains(tutorial.ID))
                continue;

            completedCount++;
            completedDurationTicks += durationTicks;
        }

        var progress = totalDurationTicks > 0
            ? (float)completedDurationTicks / totalDurationTicks
            : 0f;
        progress = Math.Clamp(progress, 0f, 1f);

        CategoryProgressBar.Value = progress;
        CategoryProgressLabel.Text = Loc.GetString(
            "tutorial-category-progress",
            ("completed", completedCount),
            ("total", tutorials.Count));
    }
}
