"Изменения: Спрайты":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Изменения: Карты":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"Изменения: Интерфейс":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"Изменения: Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Нет C#":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"
