- type: latheRecipePack
  id: HydroponicsStatic
  recipes:
  - HydroponicsToolMiniHoe
  - HydroponicsToolScythe
  - HydroponicsToolHatchet
  - HydroponicsToolSpade
  - HydroponicsToolClippers
  - PlantAnalyzer
