using System.Numerics;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._Sunrise.UserInterface.Radial;

[GenerateTypedNameReferences, Virtual, PublicAPI]
public sealed partial class RadialButton : Control
{
    [Animatable] public Vector2 Offset { get; set; }
    public string? Content { get; set; }

    public string Texture
    {
        set => Controller.TexturePath = value;
    }

    public string? Tooltip
    {
        set => Controller.ToolTip = value;
        get => Controller.ToolTip;
    }

    public float? TooltipDelay
    {
        set => Controller.TooltipDelay = value;
        get => Controller.TooltipDelay;
    }

    [Animatable]
    public Vector2 ButtonSize
    {
        get => this.Size;
        set => this.SetSize = value;
    }

    public RadialButton()
    {
        RobustXamlLoader.Load(this);
        Offset = Vector2.Zero;
    }
}
