- type: job
  id: CBURNAgentEVA
  name: job-name-cburn-eva
  description: job-description-cburn-eva
  playTimeTracker: JobCBURNAgentEVA
  setPreference: false
  startingGear: CBURNGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantERT ]

- type: job
  id: CBURNLeader
  name: job-name-cburn-leader
  description: job-description-cburn-leader
  playTimeTracker: JobCBURNLeader
  setPreference: false
  startingGear: CBURNLeaderGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantERT ]

- type: startingGear
  id: CBURNGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltERT
    outerClothing: ClothingOuterSoftsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    belt: ClothingBeltSalvageWebbing
    head: ClothingHeadSoftsuitCBURN
  storage:
    back:
    - GrenadeFlashBang
    - GrenadeFlashBang
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol
    - PillAmbuzol
    - PillAmbuzol
    - SyringeAmbuzol
    - ClothingHandsPowerGlovesUplinkNTERTCBURN
    - FireExtinguisherMini
    - MedkitCombatFilled
    - MedkitBurnFilled
    - MedkitToxinFilled
    - TacticalAxe

- type: startingGear
  id: CBURNLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltERT
    outerClothing: ClothingOuterHardsuitCBURNLeader
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    belt: ClothingBeltBandolier
  storage:
    back:
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol
    - TacticalAxe
    - ClothingHandsPowerGlovesUplinkNTERTCBURN
