- type: job
  id: CentCommFieldOfficer
  name: job-name-centcomfo
  description: job-description-centcomfo
  playTimeTracker: JobCentCommFieldOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 180000 #50 hrs
  weight: 30
  setPreference: true
  startingGear: CentCommFieldOfficerGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  radioBold: true
  canBeAntag: false
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  speciesBlacklist:
  - Vox

- type: startingGear
  id: CentCommFieldOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
