- type: job
  id: CentComOfficer
  name: job-name-centcomof
  description: job-description-centcomof
  playTimeTracker: JobCentComOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 180000 #50 hrs
  weight: 30
  setPreference: true
  startingGear: CentComOfficerGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  radioBold: true
  canBeAntag: false
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  speciesBlacklist:
  - Vox

- type: startingGear
  id: CentCommOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAdmiral
    shoes: ClothingShoesBootsJack
    head: ClothingHeadCapCentcomNaval
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCentcomNaval
    outerClothing: ClothingOuterArmorCentcomCarapace
    neck: ClothingNeckCloakCentcomAdmiral
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    pocket1: RubberStampCentcom
