- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTerminator
  name: Terminator Role
  components:
  - type: MindRole
    antagPrototype: Changeling
  - type: TerminatorRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleEvilTwin
  name: Evil Twin Role
  components:
  - type: MindRole
    antagPrototype: Changeling
  - type: EvilTwinRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFugitive
  name: Fugitive Role
  components:
  - type: MindRole
    antagPrototype: Changeling
  - type: FugitiveRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRolePlanetPrisoner
  name: Planet Prisoner Role
  components:
  - type: MindRole
    antagPrototype: Changeling
  - type: PlanetPrisonerRole
