#- type: loadout
#  id: SunriseWeaponPistolG22
#  storage:
#    back:
#    - GlockBox

- type: loadout
  id: SunriseWeaponEnergyGun
  equipment:
    pocket1: WeaponEnergyGunPistolSecurity

- type: loadout
  id: SunriseWeaponTaser
  equipment:
    pocket1: WeaponTaser
