- type: job
  id: MedicalBorg
  name: job-name-medical-borg
  description: job-description-medical-borg
  playTimeTracker: JobMedicalBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs
  icon: JobIconMedicalBorg
  supervisors: job-supervisors-human
  canBeAntag: false
  displayWeight: -10  # Sunrise
  jobEntity: PlayerBorgGenericMedical
