- type: job
  id: SecurityBorg
  name: job-name-sec-borg
  description: job-description-sec-borg
  playTimeTracker: JobSecurityBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 28800 # 8h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 hrs
  icon: JobIconSecurityBorg
  supervisors: job-supervisors-hos
  canBeAntag: false
  displayWeight: -10  # Sunrise
  jobEntity: PlayerBorgSecurityBattery
