- type: job
  id: ServiceBorg
  name: job-name-service-borg
  description: job-description-service-borg
  playTimeTracker: JobServiceBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
  icon: JobIconServiceBorg
  supervisors: job-supervisors-human
  canBeAntag: false
  displayWeight: -10  # Sunrise
  jobEntity: PlayerBorgGenericService
