- type: roleLoadout
  id: SunriseJobChiefMedicalOfficer
  groups:
  - GroupTankHarness
  - SunriseChiefMedicalOfficerHead
  - SunriseChiefMedicalOfficerMask
  - ChiefMedicalOfficerJumpsuit
  - SunriseChiefMedicalOfficerGloves
  - MedicalBackpack
  - SunriseChiefMedicalOfficerOuterClothing
  - SunriseChiefMedicalOfficerNeck
  - SunriseChiefMedicalOfficerShoes
  - SunriseChiefMedicalOfficerBra
  - SunriseChiefMedicalOfficerPants
  - SunriseGlasses
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobMedicalDoctor
  groups:
  - GroupTankHarness
  - SunriseMedicalDoctorHead
  - SunriseMedicalMask
  - MedicalDoctorJumpsuit
  - SunriseMedicalGloves
  - MedicalBackpack
  - SunriseMedicalDoctorOuterClothing
  - SunriseMedicalDoctorNeck
  - SunriseMedicalShoes
  - SunriseMedicalDoctorPDA
  - SunriseGlasses
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobMedicalIntern
  groups:
  - GroupTankHarness
  - SunriseMedicalDoctorHead
  - SunriseMedicalMask
  - MedicalInternJumpsuit
  - SunriseMedicalGloves
  - MedicalBackpack
  - SunriseMedicalDoctorOuterClothing
  - SunriseMedicalDoctorNeck
  - SunriseMedicalShoes
  - SunriseGlasses
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobChemist
  groups:
  - GroupTankHarness
  - SunriseChemistHead
  - SunriseChemistMask
  - ChemistJumpsuit
  - SunriseChemistGloves
  - ChemistBackpack
  - SunriseChemistOuterClothing
  - SunriseChemistNeck
  - SunriseChemistShoes
  - SunriseChemistMisc
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobParamedic
  groups:
  - GroupTankHarness
  - SunriseParamedicHead
  - SunriseParamedicMask
  - ParamedicJumpsuit
  - SunriseParamedicGloves
  - MedicalBackpack
  - SunriseParamedicOuterClothing
  - SunriseParamedicNeck
  - SunriseParamedicShoes
  - SunriseGlasses
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors
