- type: roleLoadout
  id: SunriseJobChiefMedicalOfficer
  groups:
  - GroupTankHarness
  - SunriseChiefMedicalOfficerHead
  - SunriseChiefMedicalOfficerMask
  - ChiefMedicalOfficerJumpsuit
  - SunriseChiefMedicalOfficerGloves
  - MedicalBackpack
  - SunriseChiefMedicalOfficerOuterClothing
  - SunriseChiefMedicalOfficerNeck
  - SunriseChiefMedicalOfficerShoes
  - MedicalEyewear
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - ChiefMedicalOfficerJobTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobMedicalDoctor
  groups:
  - GroupTankHarness
  - SunriseMedicalDoctorHead
  - SunriseMedicalMask
  - MedicalDoctorJumpsuit
  - SunriseMedicalGloves
  - MedicalBackpack
  - SunriseMedicalDoctorOuterClothing
  - SunriseMedicalDoctorNeck
  - SunriseMedicalShoes
  - SunriseMedicalDoctorPDA
  - MedicalEyewear
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - MedicalDoctorJobTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobMedicalIntern
  groups:
  - GroupTankHarness
  - SunriseMedicalDoctorHead
  - SunriseMedicalMask
  - MedicalInternJumpsuit
  - SunriseMedicalGloves
  - MedicalBackpack
  - SunriseMedicalDoctorOuterClothing
  - SunriseMedicalDoctorNeck
  - SunriseMedicalShoes
  - MedicalEyewear
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - MedicalInternJobTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobChemist
  groups:
  - GroupTankHarness
  - SunriseChemistHead
  - SunriseChemistMask
  - ChemistJumpsuit
  - SunriseChemistGloves
  - ChemistBackpack
  - SunriseChemistOuterClothing
  - SunriseChemistNeck
  - SunriseChemistShoes
  - SunriseChemistMisc
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - ChemistJobTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors

- type: roleLoadout
  id: SunriseJobParamedic
  groups:
  - GroupTankHarness
  - SunriseParamedicHead
  - SunriseParamedicMask
  - ParamedicJumpsuit
  - SunriseParamedicGloves
  - MedicalBackpack
  - SunriseParamedicOuterClothing
  - SunriseParamedicNeck
  - SunriseParamedicShoes
  - MedicalEyewear
  - SunriseSurvivalMedical
  - SunriseTrinkets
  - ParamedicJobTrinkets
  - GroupSpeciesBreathToolMedical
  - MedicalTrinkets
  - Bra
  - Pants
  - Socks
  - Contributors
