using System.Linq;
using Content.Shared._Starlight.Antags.Vampires;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Antags.Vampires;

[GenerateTypedNameReferences]
public sealed partial class VampireLocateWindow : DefaultWindow
{
    public event Action<VampireLocateTarget>? TargetSelected;

    private string _filter = string.Empty;
    private List<VampireLocateTarget> _targets = new();

    public VampireLocateWindow()
    {
        RobustXamlLoader.Load(this);

        SearchLineEdit.OnTextChanged += args =>
        {
            _filter = args.Text ?? string.Empty;
            Populate();
        };

        Populate();
    }

    public void SetTargets(IEnumerable<VampireLocateTarget> targets)
    {
        _targets = targets.ToList();
        Populate();
    }

    private void Populate()
    {
        TargetsList.DisposeAllChildren();

        var filter = _filter.Trim();
        var view = string.IsNullOrWhiteSpace(filter)
            ? _targets
            : _targets.Where(t => t.DisplayName.Contains(filter, StringComparison.CurrentCultureIgnoreCase));

        var any = false;
        foreach (var target in view)
        {
            any = true;

            var captured = target;
            var button = new Button
            {
                Text = captured.DisplayName,
                HorizontalAlignment = HAlignment.Stretch,
                ClipText = true,
            };

            button.OnPressed += _ => TargetSelected?.Invoke(captured);
            TargetsList.AddChild(button);
        }

        if (!any)
        {
            TargetsList.AddChild(new Label
            {
                Text = Loc.GetString("vampire-locate-no-targets"),
                HorizontalAlignment = HAlignment.Center,
            });
        }
    }
}
