using Content.Client._Sunrise.UserInterface.Systems.Ghost.Controls;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

public enum NewLifeRespawnBlockReason
{
    None,
    SponsorOnly,
    PrisonTimer,
    Unavailable
}

/// <summary>
/// Состояние подсветки кнопки «Тюрьма»: Red = таймер активен (достаточно игроков для старта), Yellow = хотя бы одна карта запущена, None = обычное.
/// </summary>
public enum PrisonButtonHighlightState
{
    None,
    Yellow,
    Red
}

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    // Sunrise edit - для красивой панельки призрака
    public SunriseGhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    private int _prevNumberRoles;
    public event Action? RespawnPressed; // Sunrise-Edit
    public event Action? PrisonPressed; // Sunrise-Prison
    public event Action? ChangeServerPressed;

    public void HighlightPrisonButton(PrisonButtonHighlightState state)
    {
        PrisonButton.StyleClasses.Remove(StyleClass.Negative);
        switch (state)
        {
            case PrisonButtonHighlightState.Red:
                PrisonButton.StyleClasses.Add(StyleClass.Negative);
                PrisonButton.ModulateSelfOverride = null;
                break;
            case PrisonButtonHighlightState.Yellow:
                PrisonButton.ModulateSelfOverride = Color.FromHex("#e6b800"); // золотисто-жёлтый
                break;
            default:
                PrisonButton.ModulateSelfOverride = null;
                break;
        }
    }

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        // Sunrise edit - для красивой панельки призрака
        TargetWindow = new SunriseGhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
        RespawnButton.OnPressed += _ => RespawnPressed?.Invoke(); // Sunrise-Edit
        PrisonButton.OnPressed += _ => PrisonPressed?.Invoke(); // Sunrise-Prison (подсветка не сбрасывается по клику — меняется только по состоянию: таймер/карта)
        ChangeServerButton.OnPressed += _ => ChangeServerPressed?.Invoke();
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody, NewLifeRespawnBlockReason respawnBlockReason, bool prisonRolesAvailable, string? prisonRequirementsText = null, int prisonParticipantCount = 0) // Sunrise-Edit
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        // Sunrise-Start
        RespawnButton.Text = Loc.GetString("new-life-gui-button");
        RespawnButton.Disabled = respawnBlockReason != NewLifeRespawnBlockReason.None;

        // Кнопка тюрьмы активна только если доступны роли
        PrisonButton.Text = Loc.GetString("ghost-gui-prison-button", ("count", prisonParticipantCount));
        if (prisonRolesAvailable)
        {
            PrisonButton.Disabled = false;
            PrisonButton.ToolTip = null;
        }
        else
        {
            PrisonButton.Disabled = true;
            PrisonButton.ToolTip = prisonRequirementsText ?? "No prison roles available";
        }
        // Sunrise-End

        TargetWindow.Populate();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
