using Content.Client._Sunrise.Sandbox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.UserInterface.Systems.Sandbox.Widgets;

[GenerateTypedNameReferences]
public sealed partial class MappingAccessWidget : UIWidget
{
    public event Action<MappingAccessBodyFilter>? FilterChanged;
    public event Action<bool>? ElectronicsOnlyChanged;

    public MappingAccessWidget()
    {
        RobustXamlLoader.Load(this);
        Visible = false;

        TitleLabel.FontColorOverride = Color.Aquamarine;

        AddFilterOption(MappingAccessBodyFilter.Both, "mapping-access-widget-filter-both");
        AddFilterOption(MappingAccessBodyFilter.Static, "mapping-access-widget-filter-static");
        AddFilterOption(MappingAccessBodyFilter.Dynamic, "mapping-access-widget-filter-dynamic");
        ElectronicsOnlyCheckBox.OnToggled += args => ElectronicsOnlyChanged?.Invoke(args.Pressed);
        BodyFilterOptionButton.OnItemSelected += OnBodyFilterSelected;
        BodyFilterOptionButton.SelectId((int) MappingAccessBodyFilter.Both);
    }

    public void SetBodyFilter(MappingAccessBodyFilter filter)
    {
        BodyFilterOptionButton.SelectId((int) filter);
    }

    public void SetElectronicsOnly(bool electronicsOnly)
    {
        ElectronicsOnlyCheckBox.Pressed = electronicsOnly;
    }

    private void AddFilterOption(MappingAccessBodyFilter filter, string locKey)
    {
        BodyFilterOptionButton.AddItem(Loc.GetString(locKey), (int) filter);
        BodyFilterOptionButton.SetItemMetadata(BodyFilterOptionButton.GetIdx((int) filter), filter);
    }

    private void OnBodyFilterSelected(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.SelectId(args.Id);

        if (args.Button.SelectedMetadata is MappingAccessBodyFilter filter)
            FilterChanged?.Invoke(filter);
    }
}
