using Content.Client._Sunrise.Sandbox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Sunrise.UserInterface.Systems.Sandbox.Widgets;

[GenerateTypedNameReferences]
public sealed partial class MappingTransparencyWidget : UIWidget
{
    public event Action<int>? TransparencyChanged;

    public MappingTransparencyWidget()
    {
        RobustXamlLoader.Load(this);

        TitleLabel.FontColorOverride = Color.Aquamarine;

        TransparencySlider.Rounded = true;
        TransparencySlider.MinValue = MappingTransparencySystem.MinTransparencyPercent;
        TransparencySlider.MaxValue = MappingTransparencySystem.MaxTransparencyPercent;
        TransparencySlider.OnValueChanged += _ => OnTransparencySliderChanged();

        SetTransparencyPercent(MappingTransparencySystem.DefaultTransparencyPercent);
    }

    public void SetTransparencyPercent(int percent)
    {
        TransparencySlider.SetValueWithoutEvent(percent);
        TransparencyValueLabel.Text = Loc.GetString("mapping-transparency-widget-value", ("value", percent));
    }

    private void OnTransparencySliderChanged()
    {
        var percent = (int) TransparencySlider.Value;
        TransparencyValueLabel.Text = Loc.GetString("mapping-transparency-widget-value", ("value", percent));
        TransparencyChanged?.Invoke(percent);
    }
}
