using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Proton;

[GenerateTypedNameReferences]
public sealed partial class ProtonScreenshotView : FancyWindow
{
    public ProtonScreenshotView(Texture image)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TextureRect.Texture = image;
        TextureRect.TextureScale = new Vector2(0.7f, 0.7f);
    }
}
