// © SUNRISE, An EULA/CLA with a hosting restriction, full text: https://github.com/space-sunrise/space-station-14/blob/master/CLA.txt
using Content.Client._Sunrise.ServersHub;
using Content.Shared._Sunrise.ServersHub;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.SponsorTiers;

[GenerateTypedNameReferences]
public sealed partial class SponsorTiersUi : DefaultWindow
{
    [Dependency] private readonly ServersHubManager _serversHubManager = default!;

    public SponsorTiersUi()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _serversHubManager.ServersDataListChanged += RefreshServersHubHeader;
    }

    private void RefreshServersHubHeader(List<ServerHubEntry> servers)
    {

    }
}
