using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.SponsorTiers;

[GenerateTypedNameReferences]
public sealed partial class SponsorTiersUi : DefaultWindow
{
    public SponsorTiersUi()
    {
        RobustXamlLoader.Load(this);
    }
}
