- type: job
  id: SeniorPhysician
  name: job-name-morgue-attendant
  description: job-description-morgue-attendant
  playTimeTracker: JobMorgueAttendant
  requirements:
    - !type:RoleTimeRequirement
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 216000 # 60 hrs
  startingGear: MorgueAttendantGear
  icon: "JobIconMorgueAttendant"
  supervisors: job-supervisors-cmo
  displayWeight: 35
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: MorgueAttendantGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabSeniorPhysician
