- type: job
  id: MedicalSurgeon
  name: job-name-Surgeon
  description: job-description-Surgeon
  playTimeTracker: JobMedicalSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs # Corvax-RoleTime
  startingGear: SurgeonGear
  icon: "JobIconSurgeon"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: SurgeonGear
  equipment:
    id: SurgeonPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    
- type: jobIcon
  parent: JobIcon
  id: JobIconSurgeon
  icon:
    sprite: /Textures/_Sunrise/Interface/Misc/job_icons.rsi
    state: Surgeon

- type: chameleonOutfit
  id: MedicalSurgeonChameleonOutfit
  job: MedicalSurgeon
  equipment:
    gloves: ClothingHandsGlovesLatex
    head: ClothingHeadHatBeretSurgeon
    mask: ClothingMaskBreath
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatSurgeon