using Content.Shared._Sunrise.NewLife;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Sunrise.NewLife
{
    [GenerateTypedNameReferences]
    public sealed partial class NewLifeWindow : DefaultWindow
    {
        private readonly IGameTiming _timing;

        private TimeSpan _nextRespawnTime = TimeSpan.Zero;

        private List<int> _usedCharacters = [];

        private Dictionary<NetEntity, List<NewLifeRolesInfo>> _jobs = new();

        public Action? SpawnRequested;

        public NewLifeWindow(IGameTiming timing)
        {
            RobustXamlLoader.Load(this);
            _timing = timing;
            Spawn.OnPressed += OnSpawnPressed;

            CharacterSelector.OnItemSelected += args =>
            {
                CharacterSelector.Select(args.Id);
            };

            StationSelector.OnItemSelected += args =>
            {
                var metadata = StationSelector.GetItemMetadata(args.Id);
                if (metadata is not NetEntity cast)
                    return;
                RoleSelector.Clear();
                UpdateRolesList(_jobs[cast]);
                StationSelector.Select(args.Id);
            };

            RoleSelector.OnItemSelected += args =>
            {
                RoleSelector.Select(args.Id);
            };
        }

        private void OnSpawnPressed(BaseButton.ButtonEventArgs obj)
        {
            var selectedCharacter = GetSelectedCharacter();
            if (selectedCharacter == null || _usedCharacters.Contains(selectedCharacter.Value))
                return;
            if (_timing.CurTime < _nextRespawnTime)
                return;
            SpawnRequested?.Invoke();
        }

        public int? GetSelectedCharacter()
        {
            var characterId = (int?) CharacterSelector.SelectedMetadata;
            return characterId;
        }

        public string? GetSelectedRole()
        {
            var roleId = (string?) RoleSelector.SelectedMetadata;
            return roleId;
        }

        public NetEntity? GetSelectedStation()
        {
            var roleId = (NetEntity?) StationSelector.SelectedMetadata;
            return roleId;
        }

        public void UpdateNextRespawn(TimeSpan nextRespaw)
        {
            _nextRespawnTime = nextRespaw;
        }

        public void UpdateCharactersList(List<NewLifeCharacterInfo> characters, List<int> usedCharactersForRespawn)
        {
            _usedCharacters = usedCharactersForRespawn;
            for (var i = 0; i < characters.Count; i++)
            {
                var character = characters[i];
                CharacterSelector.AddItem($"{character.Name}", i);
                CharacterSelector.SetItemMetadata(i, character.Identifier);
                if (usedCharactersForRespawn.Contains(character.Identifier))
                {
                    //CharacterSelector.SetItemDisabled(CharacterSelector.GetIdx(i), true);
                    CharacterSelector.SetItemText(CharacterSelector.GetIdx(i), Loc.GetString("new-life-gui-character-used", ("name", character.Name)));
                }
            }
        }

        public void UpdateStationList(Dictionary<NetEntity, string> stations, NetEntity selectedStation)
        {
            StationSelector.Clear();

            if (stations.Count == 0)
                return;

            foreach (var (stationUid, stationName) in stations)
            {
                StationSelector.AddItem(stationName);
                StationSelector.SetItemMetadata(StationSelector.ItemCount - 1, stationUid);

                if (stationUid == selectedStation)
                {
                    StationSelector.Select(StationSelector.ItemCount - 1);
                }
            }
        }

        public void UpdateRolesList(List<NewLifeRolesInfo> roles)
        {
            for (var i = 0; i < roles.Count; i++)
            {
                var role = roles[i];
                var count = role.Count.HasValue ? role.Count.ToString() : "\u221e";
                RoleSelector.AddItem($"{role.Name} [{count}]", i);
                RoleSelector.SetItemMetadata(i, role.Identifier);
            }
        }

        public void UpdateJobs(Dictionary<NetEntity, List<NewLifeRolesInfo>> jobs)
        {
            _jobs = jobs;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            var selectedCharacter = GetSelectedCharacter();
            if (selectedCharacter != null && _usedCharacters.Contains(selectedCharacter.Value))
            {
                Spawn.Disabled = true;
                NextRespawnLabelTitle.Text = Loc.GetString("new-life-gui-character-not-available");
                NextRespawnLabel.Visible = false;
                return;
            }

            var selectedStation = GetSelectedStation();
            var selectedRole = GetSelectedRole();
            if (selectedStation != null && selectedRole != null)
            {
                foreach (var role in _jobs[selectedStation.Value])
                {
                    if (selectedRole != role.Identifier || role.Count != 0)
                        continue;
                    Spawn.Disabled = true;
                    NextRespawnLabelTitle.Text = Loc.GetString("new-life-gui-role-not-available");
                    NextRespawnLabel.Visible = false;
                    return;
                }
            }

            if (_timing.CurTime < _nextRespawnTime)
            {
                Spawn.Disabled = true;
                NextRespawnLabelTitle.Text = Loc.GetString("new-life-gui-available-via");
                NextRespawnLabel.Visible = true;
                var remaining = TimeSpan.FromSeconds(Math.Max((_nextRespawnTime - _timing.CurTime).TotalSeconds, 0));
                NextRespawnLabel.Text = $" {remaining:mm':'ss}";
                return;
            }
            Spawn.Disabled = false;
            NextRespawnLabelTitle.Text = Loc.GetString("new-life-gui-available");
            NextRespawnLabel.Visible = false;
        }
    }
}
