- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 18000 #5 hrs # Sunrise-RoleTime
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs # Sunrise-RoleTime
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  radioBold: true
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    head: ClothingHeadHatHardhatWhite
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - Flash
