using Content.Shared._Sunrise.TapeRecorder;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Sunrise.TapeRecorder;

[GenerateTypedNameReferences]
public sealed partial class TapeRecorderMenu : FancyWindow
{
    public event Action<TapeRecorderMode>? OnModePressed;
    public event Action? OnPrintPressed;

    public TapeRecorderMenu()
    {
        RobustXamlLoader.Load(this);

        StopButton.OnPressed += _ => OnModePressed?.Invoke(TapeRecorderMode.Stopped);
        RecordButton.OnPressed += _ => OnModePressed?.Invoke(TapeRecorderMode.Recording);
        PlayButton.OnPressed += _ => OnModePressed?.Invoke(TapeRecorderMode.Playing);
        RewindButton.OnPressed += _ => OnModePressed?.Invoke(TapeRecorderMode.Rewinding);
        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void UpdateState(TapeRecorderBoundUserInterfaceState state)
    {
        CassetteLabel.Text = Loc.GetString(
            "tape-recorder-ui-cassette",
            ("cassette", state.CassetteName));

        PlaybackTimeline.UpdateState(state.Position, state.Capacity, state.RecordedRanges);

        TimeLabel.Text = Loc.GetString(
            "tape-recorder-ui-time",
            ("position", FormatTime(state.Position)),
            ("capacity", FormatTime(state.Capacity)),
            ("remaining", FormatTime(state.Capacity > state.Position ? state.Capacity - state.Position : TimeSpan.Zero)),
            ("records", state.RecordCount));

        StopButton.Disabled = state.Mode == TapeRecorderMode.Stopped;
        RecordButton.Disabled = !state.HasCassette || !state.CanRecord;
        PlayButton.Disabled = !state.HasCassette || !state.CanPlay;
        RewindButton.Disabled = !state.HasCassette || state.Position <= TimeSpan.Zero;
        PrintButton.Disabled = !state.HasCassette || state.RecordCount == 0;

        RecordButton.ModulateSelfOverride = state.Mode == TapeRecorderMode.Recording ? Color.DarkGreen : null;
        PlayButton.ModulateSelfOverride = state.Mode == TapeRecorderMode.Playing ? Color.DarkGreen : null;
        RewindButton.ModulateSelfOverride = state.Mode == TapeRecorderMode.Rewinding ? Color.DarkGreen : null;
    }

    private static string FormatTime(TimeSpan time) =>
        time.ToString(@"mm\:ss");
}
