- type: gameMap
  id: SunriseMeta
  mapName: 'Meta Station'
  mapPath: /Maps/_Sunrise/Station/meta.yml
  maxRandomOffset: 0
  randomRotation: false
  minPlayers: 0
  stations:
    Meta:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: '{0} Мета {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'TG'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/_Sunrise/Shuttles/emergency_meta.yml
        - type: StationJobs
          availableJobs:
            #service
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            NanoTrasenRepresentative: [ 1, 1 ]
            Adjutant: [ 1, 1 ]
            Bartender: [ 2, 2 ]
            Botanist: [ 2, 3 ]
            Chef: [ 2, 2 ]
            Janitor: [ 1, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ -1, -1 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 5, 7 ]
            TechnicalAssistant: [ -1, -1 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 5, 5 ]
            MedicalIntern: [ -1, -1 ]
            Paramedic: [ 1, 1 ]
            #science
            ResearchDirector: [ 1, 1 ]
            Scientist: [ 5, 7 ]
            ResearchAssistant: [ -1, -1 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 5, 7 ]
            SecurityPilot: [ 1, 1 ]
            Detective: [ 1, 1 ]
            SecurityCadet: [ -1, -1 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            # Sunrise-Security
            Brigmedic: [ 1, 1 ]
            # Sunrise-BlueShield
            BlueShield: [ 1, 1 ]
            # Sunrise-Law
            IAA: [ 1, 1 ]
            Lawyer: [ 2, 2 ]
            Magistrat: [ 1, 1 ]
            # Sunrise-Senior
            SeniorEngineer: [ 1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            # Sunrise-Science
            Roboticist: [ 2, 2 ]
            # silicon
            StationAi: [ 1, 1 ]
            Borg: [ 2, 2 ]
            MedicalBorg: [ 4, 4 ]
            EngineerBorg: [ 2, 2 ]
            MinerBorg: [ 2, 2 ]
            JanitorBorg: [ 2, 2 ]
            ServiceBorg: [ 2, 2 ]
            ClownBorg: [ 2, 2 ]
            PeaceBorg: [ 2, 2 ]
            SecurityBorg: [ 4, 4 ]
            SecurityCombatBorg: [ 2, 2 ]
            # Sunrise-Civillian
            Barber: [ 1, 1 ]
        - type: StationGoal
          goals:
          - Shuttle
          - Singularity
          - SolarPanels
          - Artifacts
          - Bank
          - Zoo
          - MiningOutpost
          - Tesla
          - XenobiologyRepair
          - VirusologyAmbusol
          - Containment
          - WeaponsSecurity
          - MaintsRepair
          - DormsBuild
          - BattleShuttle
          - Transit
          - NukeRoom
          - Permabrig
          - Farm

