- type: gameMap
  id: SunriseTrain
  mapName: 'Train'
  mapPath: /Maps/_Sunrise/Station/train.yml
  maxRandomOffset: 0
  randomRotation: false
  minPlayers: 0
  maxPlayers: 40
  stations:
    Train:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Поезд "Многоножка" {0}-{1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/_Sunrise/Shuttles/emergency_omega.yml # TODO - add railway station
        - type: StationJobs
          availableJobs:
            #command
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            NanoTrasenRepresentative: [ 1, 1 ]
            Adjutant: [ 1, 1 ]
            #service
            Bartender: [ 2, 2 ]
            Botanist: [ 3, 3 ]
            Chef: [ 2, 2 ]
            Janitor: [ 2, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ -1, -1 ]
            Reporter: [ 2, 2 ]
            Zookeeper: [ 1, 1 ]
            Barber: [ 1, 1 ]
            #engineering
            ChiefEngineer: [ 1, 1 ]
            SeniorEngineer: [ 1, 1 ]
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 5, 5 ]
            TechnicalAssistant: [ -1, -1 ]
            #medical
            ChiefMedicalOfficer: [ 1, 1 ]
            SeniorPhysician: [ 1, 1 ]
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 4, 4 ]
            Paramedic: [ 1, 1 ]
            MedicalIntern: [ -1, -1 ]
            Psychologist: [ 1, 1 ]
            MedicalPathologist: [ 1, 1 ]
            #science
            ResearchDirector: [ 1, 1 ]
            SeniorResearcher: [ 1, 1 ]
            Scientist: [ 5, 5 ]
            ResearchAssistant: [ -1, -1 ]
            Roboticist: [ 2, 2 ]
            #security
            HeadOfSecurity: [ 1, 1 ]
            Warden: [ 1, 1 ]
            SeniorOfficer: [ 1, 1 ]
            Detective: [ 1, 1 ]
            Brigmedic: [ 1, 1 ]
            #SecurityPilot: [ 1, 1 ]
            SecurityOfficer: [ 5, 5 ]
            SecurityCadet: [ -1, -1 ]
            #supply
            Quartermaster: [ 1, 1 ]
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            #civilian
            Passenger: [ -1, -1 ]
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            #blueshield
            BlueShield: [ 1, 1 ]
            #law
            IAA: [ 1, 1 ]
            Lawyer: [ 2, 2 ]
            Magistrat: [ 1, 1 ]
            #silicon
            StationAi: [ 1, 1 ]
            Borg: [ 22, 22 ]
            SecurityCombatBorg: [ 2, 2 ]
        - type: StationGoal
          goals:
          - Shuttle
          - Singularity
          - SolarPanels
          - Artifacts
          - Bank
          - Zoo
          - MiningOutpost
          - Tesla
          - XenobiologyRepair
          - VirusologyAmbusol
          - Containment
          - WeaponsSecurity
          - MaintsRepair
          - DormsBuild
          - BattleShuttle
          - Transit
          - NukeRoom
          - Permabrig
          - Farm
          - Delegates
          - Cyborgs
          - Testing
          - Anomaly
          - Replenishment
          - IntelWeapons
          - Reports
          - Reconnaissance
          - Saboteurs
          - Furs
          - Crew
