- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
  startingGear: ZookeeperGear
  icon: "JobIconZookeeper"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MonkeyDay
    prototype: MonkeyCubeBox

- type: startingGear
  id: ZookeeperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSafari
    head: ClothingHeadSafari
    shoes: ClothingShoesColorWhite
    id: ZookeeperPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - ZookeeperMedkitFilled # Аптечка первой помощи для первых пациентов

- type: chameleonOutfit
  id: ZookeeperChameleonOutfit
  job: Zookeeper
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorLightBrown
    neck: ClothingNeckScarfStripedBrown
    belt: ClothingBeltStorageWaistbag
    gloves: ClothingHandsGlovesColorBrown

- type: entity
  id: ZookeeperMedkitFilled
  parent: MedkitFilled
  name: "аптечка зоотехника"
  description: "Внутри не только бинты и таблетки, но и специальный шприц с успокоительным."
  components:
  - type: StorageFill
    contents:
    - id: Brutepack
    - id: Ointment
    - id: Gauze
    - id: PillCanisterTricordrazine
    - id: ZookeeperSyringeChloralHydrate

- type: entity
  id: ZookeeperSyringeChloralHydrate
  parent: PrefilledSyringe
  name: шприц хлоральгидрата
  suffix: хлоральгидрат
  components:
  - type: Label
    currentLabel: reagent-name-chloral-hydrate
  - type: SolutionContainerManager
    solutions:
      injector:
        maxVol: 15
        reagents:
        - ReagentId: ChloralHydrate
          Quantity: 15
