using Content.Shared._Sunrise.CopyMachine;
using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Serialization.TypeSerializers.Implementations;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.CopyMachine;

[GenerateTypedNameReferences]
public sealed partial class CopyMachineMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<string?>? OnPrintPressed;
    public event Action? OnCopyPressed;
    public event Action<int>? OnCancelQueueJobPressed;

    private const int MaxListLabelLength = 64;
    private const float ListIconTargetSize = 40f;
    private const float ListIconScaleMin = 0.1f;
    private const float ListIconScaleMax = 2.5f;

    private string? _currentTemplate;
    private bool _canCopy;
    private float _incVolume;
    private string _searchText = string.Empty;
    private List<string> _allTemplates = new();
    private string? _activeComponentFilter = null;
    private bool _suppressCategorySelection;

    private readonly Dictionary<string, Texture> _componentIconTextures = new();
    private readonly List<string?> _categoryFilterById = new();

    private Texture? _printIconTexture;
    private Texture? _copyIconTexture;
    private string _copyStatusText = string.Empty;

    private static readonly string[] AllowedComponents =
    {
        "CentcomStandard", "CentcomStrict", "Command", "Engineering", "Justice", "Medical", "Science",
        "Security", "Service", "Supply", "Syndicate", "General", "Prison"
    };

    private static readonly ResPath JobIconRsiPath = new("/Textures/Interface/Misc/job_icons.rsi");
    private static readonly Dictionary<string, string> ComponentIconStates = new()
    {
        ["CentcomStandard"] = "Nanotrasen",
        ["CentcomStrict"] = "Nanotrasen",
        ["Command"] = "Captain",
        ["Engineering"] = "StationEngineer",
        ["Justice"] = "Lawyer",
        ["Medical"] = "MedicalDoctor",
        ["Science"] = "Scientist",
        ["Security"] = "SecurityOfficer",
        ["Service"] = "ServiceWorker",
        ["Supply"] = "CargoTechnician",
        ["Syndicate"] = "Syndicate",
        ["General"] = "Passenger",
        ["Prison"] = "Prisoner",
    };

    private static readonly ResPath CopyMachineActionsRsiPath = new("/Textures/_Sunrise/Interface/CopyMachine/copy_machine_actions.rsi");
    private const string PrintIconState = "print";
    private const string CopyIconState = "copy";

    public CopyMachineMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke(_currentTemplate);
        CopyButton.OnPressed += _ => OnCopyPressed?.Invoke();

        PrintIcon.Texture = GetPrintIconTexture();
        CopyIcon.Texture = GetCopyIconTexture();

        TemplateList.OnItemSelected += OnTemplateSelected;
        TemplateList.OnItemDeselected += OnTemplateDeselected;

        SearchBar.OnTextChanged += _ =>
        {
            _searchText = SearchBar.Text.Trim();
            PopulateTemplates();
        };

        CategoryDropdown.OnItemSelected += OnCategorySelected;
        RebuildFilterButtons();
    }

    private void OnTemplateSelected(ItemList.ItemListSelectedEventArgs args)
    {
        _currentTemplate = args.ItemList[args.ItemIndex].Metadata as string;
        PrintButton.Disabled = _incVolume <= 0.0f || _currentTemplate == null;
    }

    private void OnTemplateDeselected(ItemList.ItemListDeselectedEventArgs args)
    {
        _currentTemplate = null;
        PrintButton.Disabled = true;
    }

    public void UpdateState(CopyMachineBoundUserInterfaceState state)
    {
        var templatesChanged = !TemplatesEqual(_allTemplates, state.Templates);

        _canCopy = state.CanCopy;
        _incVolume = state.InkAmount;

        if (templatesChanged)
            _allTemplates = state.Templates;

        UpdateStats(state);
        UpdateButtons();
        UpdateCurrentJob(state);
        UpdateQueue(state);

        if (templatesChanged)
        {
            RebuildFilterButtons();
            PopulateTemplates();
        }
    }

    private void UpdateStats(CopyMachineBoundUserInterfaceState state)
    {
        PaperCountLabel.Text = state.PaperCount.ToString();
        InkAmountLabel.Text = _incVolume.ToString("F1");

        _copyStatusText = _canCopy
            ? Loc.GetString("copy-machine-menu-copy-available")
            : Loc.GetString("copy-machine-menu-copy-unavailable");

        CopyButton.ToolTip = $"{Loc.GetString("copy-machine-menu-copy")}\n{_copyStatusText}";
    }

    private void UpdateButtons()
    {
        PrintButton.Disabled = _currentTemplate == null || _incVolume <= 0.0f;
        CopyButton.Disabled = !_canCopy;
    }

    private void UpdateCurrentJob(CopyMachineBoundUserInterfaceState state)
    {
        var currentJobText = state.CurrentJob?.ToString() ?? Loc.GetString("copy-machine-menu-no-active-job");
        CurrentJobLabel.Text = Ellipsize(currentJobText, MaxListLabelLength);
        CurrentJobLabel.ToolTip = currentJobText;
    }

    private void UpdateQueue(CopyMachineBoundUserInterfaceState state)
    {
        QueueContainer.RemoveAllChildren();

        for (var i = 0; i < state.Queue.Count; i++)
        {
            var job = state.Queue[i];
            var fullText = job.ToString();
            var icon = job.Type switch
            {
                CopyMachineJobType.Print => GetPrintIconTexture(),
                CopyMachineJobType.Copy => GetCopyIconTexture(),
                _ => null
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(2, 1),
                SeparationOverride = 4
            };

            if (icon != null)
            {
                row.AddChild(new TextureRect
                {
                    Texture = icon,
                    SetSize = new(16, 16),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    VerticalAlignment = VAlignment.Center,
                    CanShrink = true
                });
            }

            var label = new Label
            {
                Text = Ellipsize(fullText, MaxListLabelLength),
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = fullText
            };

            var cancelButton = new TextureButton();
            cancelButton.AddStyleClass("windowCloseButton");
            cancelButton.ToolTip = Loc.GetString("copy-machine-menu-cancel-job");

            var index = i;
            cancelButton.OnPressed += _ => OnCancelQueueJobPressed?.Invoke(index);

            row.AddChild(label);
            row.AddChild(cancelButton);
            QueueContainer.AddChild(row);
        }
    }

    private static bool TemplatesEqual(List<string> a, List<string> b)
    {
        if (ReferenceEquals(a, b))
            return true;

        if (a.Count != b.Count)
            return false;

        for (var i = 0; i < a.Count; i++)
        {
            if (a[i] != b[i])
                return false;
        }

        return true;
    }

    private void RebuildFilterButtons()
    {
        _suppressCategorySelection = true;
        CategoryDropdown.Clear();
        _categoryFilterById.Clear();

        CategoryDropdown.AddItem(Loc.GetString("copy-machine-filter-all"), 0);
        _categoryFilterById.Add(null);

        var countsByComponent = GetUsedComponentCounts();
        foreach (var component in AllowedComponents)
        {
            if (!countsByComponent.TryGetValue(component, out var count) || count <= 0)
                continue;

            var localized = Loc.GetString($"copy-machine-component-{component}");

            CategoryDropdown.AddItem($"{localized} ({count})", _categoryFilterById.Count);
            _categoryFilterById.Add(component);
        }

        var selectedId = 0;
        if (_activeComponentFilter != null)
            selectedId = _categoryFilterById.IndexOf(_activeComponentFilter);

        if (selectedId <= 0)
        {
            _activeComponentFilter = null;
            selectedId = 0;
        }

        CategoryDropdown.SelectId(selectedId);
        _suppressCategorySelection = false;
    }

    private Dictionary<string, int> GetUsedComponentCounts()
    {
        var counts = new Dictionary<string, int>();

        foreach (var component in AllowedComponents)
        {
            counts[component] = 0;
        }

        foreach (var templateId in _allTemplates)
        {
            if (!_protoManager.TryIndex<DocTemplatePrototype>(templateId, out var template))
                continue;

            if (counts.ContainsKey(template.Component))
                counts[template.Component]++;
        }

        return counts;
    }

    private void OnCategorySelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_suppressCategorySelection)
            return;

        if (args.Id < 0 || args.Id >= _categoryFilterById.Count)
            return;

        SetActiveComponentFilter(_categoryFilterById[args.Id]);
        args.Button.SelectId(args.Id);
    }

    private void SetActiveComponentFilter(string? component)
    {
        _activeComponentFilter = component;
        PopulateTemplates();
    }

    private void PopulateTemplates()
    {
        var previouslySelected = _currentTemplate;
        _currentTemplate = null;
        TemplateList.Clear();

        var filtered = GetFilteredTemplates();
        var shouldGroupByComponent = _activeComponentFilter == null && string.IsNullOrWhiteSpace(_searchText);

        if (shouldGroupByComponent)
        {
            var templatesByComponent = new Dictionary<string, List<TemplateEntry>>();
            foreach (var templateId in filtered)
            {
                if (!_protoManager.TryIndex<DocTemplatePrototype>(templateId, out var template))
                    continue;

                var component = template.Component;
                if (!templatesByComponent.TryGetValue(component, out var templates))
                {
                    templates = new List<TemplateEntry>();
                    templatesByComponent[component] = templates;
                }

                templates.Add(new TemplateEntry(templateId, template, Loc.GetString(template.Name)));
            }

            foreach (var component in AllowedComponents)
            {
                if (!templatesByComponent.TryGetValue(component, out var templates) || templates.Count == 0)
                    continue;

                AddComponentHeader(component, templates.Count);

                templates.Sort(static (a, b) => string.Compare(a.SortName, b.SortName, StringComparison.CurrentCulture));
                foreach (var entry in templates)
                {
                    AddTemplateItem(entry.TemplateId, entry.Template, entry.FullName);
                }
            }
        }

        else
        {
            foreach (var templateId in filtered)
            {
                if (!_protoManager.TryIndex<DocTemplatePrototype>(templateId, out var template))
                    continue;

                AddTemplateItem(templateId, template);
            }
        }

        if (previouslySelected != null)
        {
            for (var i = 0; i < TemplateList.Count; i++)
            {
                if (TemplateList[i].Metadata as string != previouslySelected)
                    continue;

                TemplateList[i].Selected = true;
                break;
            }
        }

        PrintButton.Disabled = _currentTemplate == null || _incVolume <= 0.0f;
    }

    private readonly struct TemplateEntry
    {
        public readonly string TemplateId;
        public readonly DocTemplatePrototype Template;
        public readonly string SortName;
        public readonly string FullName;

        public TemplateEntry(string templateId, DocTemplatePrototype template, string fullName)
        {
            TemplateId = templateId;
            Template = template;
            SortName = fullName;
            FullName = fullName;
        }
    }

    private void AddComponentHeader(string component, int count)
    {
        var localized = Loc.GetString($"copy-machine-component-{component}");
        var icon = GetComponentIconTexture(component);
        var headerText = $"——— {localized} ({count}) ———";
        var item = TemplateList.AddItem(headerText, icon, selectable: false);
        item.TooltipEnabled = false;

        if (icon != null)
            item.IconScale = GetIconScale(icon);
    }

    private void AddTemplateItem(string templateId, DocTemplatePrototype template)
    {
        AddTemplateItem(templateId, template, Loc.GetString(template.Name));
    }

    private void AddTemplateItem(string templateId, DocTemplatePrototype template, string fullName)
    {
        var icon = GetComponentIconTexture(template.Component);
        var item = TemplateList.AddItem(Ellipsize(fullName, MaxListLabelLength), icon, metadata: templateId);
        item.TooltipText = fullName;

        if (icon == null)
            return;

        item.IconScale = GetIconScale(icon);
    }

    private List<string> GetFilteredTemplates()
    {
        var result = new List<string>();
        foreach (var id in _allTemplates)
        {
            if (PassesFilter(id))
                result.Add(id);
        }

        return result;
    }

    private bool PassesFilter(string id)
    {
        if (!_protoManager.TryIndex<DocTemplatePrototype>(id, out var proto))
            return false;

        if (_activeComponentFilter != null && proto.Component != _activeComponentFilter)
            return false;

        if (string.IsNullOrWhiteSpace(_searchText))
            return true;

        var name = Loc.GetString(proto.Name).ToLowerInvariant();
        var idLower = id.ToLowerInvariant();
        var search = _searchText.ToLowerInvariant();

        return name.Contains(search) || idLower.Contains(search);
    }

    private Texture? GetComponentIconTexture(string component)
    {
        if (string.IsNullOrWhiteSpace(component))
            return null;

        if (_componentIconTextures.TryGetValue(component, out var cached))
            return cached;

        if (!ComponentIconStates.TryGetValue(component, out var state))
            return null;

        var texture = TryGetRsiStateTexture(JobIconRsiPath, state);
        if (texture == null)
            return null;

        _componentIconTextures[component] = texture;
        return texture;
    }

    private Texture? GetPrintIconTexture()
    {
        _printIconTexture ??= TryGetRsiStateTexture(CopyMachineActionsRsiPath, PrintIconState);
        return _printIconTexture;
    }

    private Texture? GetCopyIconTexture()
    {
        _copyIconTexture ??= TryGetRsiStateTexture(CopyMachineActionsRsiPath, CopyIconState);
        return _copyIconTexture;
    }

    // Почему бы и нет?
    private Texture? TryGetRsiStateTexture(ResPath rsiPath, string state)
    {
        if (!_resourceCache.TryGetResource<RSIResource>(SpriteSpecifierSerializer.TextureRoot / rsiPath, out var rsi))
            return null;

        return rsi.RSI.TryGetState(state, out var rsiState) ? rsiState.Frame0 : null;
    }

    private static float GetIconScale(Texture texture)
    {
        var target = ListIconTargetSize;
        if (texture.Size.Y <= 0)
            return 1f;

        return Math.Clamp(target / texture.Size.Y, ListIconScaleMin, ListIconScaleMax);
    }

    private static string Ellipsize(string text, int maxLength)
    {
        if (maxLength <= 0)
            return string.Empty;

        if (text.Length <= maxLength)
            return text;

        if (maxLength <= 3)
            return text[..maxLength];

        return $"{text[..(maxLength - 3)]}...";
    }
}
