using System.Linq;
using Content.Shared._Sunrise.Messenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.GameObjects;
using Content.Shared.StatusIcon;
using Robust.Client.UserInterface;

namespace Content.Client._Sunrise.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class AddUserDialog : DefaultWindow
{
    public event Action<string>? OnUserSelected;

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;

    private List<MessengerUser> _availableUsers = new();

    private SpriteSystem GetSpriteSystem() => _entitySystemManager.GetEntitySystem<SpriteSystem>();

    public AddUserDialog()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("messenger-add-user-title");

        SearchInput.OnTextChanged += _ => UpdateUsersList();
    }

    public void SetTitle(string title)
    {
        Title = title;
    }

    public void SetAvailableUsers(List<MessengerUser> users)
    {
        _availableUsers = users;
        UpdateUsersList();
    }

    private void UpdateUsersList()
    {
        UsersList.RemoveAllChildren();
        var searchText = SearchInput.Text.ToLowerInvariant();

        var filteredUsers = _availableUsers.Where(u =>
            string.IsNullOrEmpty(searchText) ||
            (u.Name?.ToLowerInvariant().Contains(searchText) ?? false))
            .ToList();

        foreach (var user in filteredUsers)
        {
            var userButton = new Button
            {
                HorizontalExpand = true,
                Margin = new Thickness(2)
            };

            var buttonContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(4, 0)
            };

            CreateJobIconRect(user.JobIconId, buttonContainer);

            var nameLabel = new Label
            {
                Text = user.Name,
                HorizontalExpand = true,
                Margin = new Thickness(4, 0)
            };
            buttonContainer.AddChild(nameLabel);

            userButton.AddChild(buttonContainer);

            var userId = user.UserId;
            userButton.OnPressed += _ =>
            {
                OnUserSelected?.Invoke(userId);
                Close();
            };

            UsersList.AddChild(userButton);
        }
    }

    private void CreateJobIconRect(ProtoId<JobIconPrototype>? jobIconId, Control container)
    {
        if (jobIconId != null && _prototypeManager.TryIndex(jobIconId.Value, out JobIconPrototype? jobIcon))
        {
            var iconRect = new TextureRect
            {
                Texture = GetSpriteSystem().Frame0(jobIcon.Icon),
                SetWidth = 20,
                SetHeight = 20,
                Stretch = TextureRect.StretchMode.Scale,
                Margin = new Thickness(0, 0, 4, 0)
            };
            container.AddChild(iconRect);
        }
        else
        {
            var unknownIconId = new ProtoId<JobIconPrototype>("JobIconUnknown");
            if (_prototypeManager.TryIndex(unknownIconId, out JobIconPrototype? unknownIcon))
            {
                var iconRect = new TextureRect
                {
                    Texture = GetSpriteSystem().Frame0(unknownIcon.Icon),
                    SetWidth = 20,
                    SetHeight = 20,
                    Stretch = TextureRect.StretchMode.Scale,
                    Margin = new Thickness(0, 0, 4, 0)
                };
                container.AddChild(iconRect);
            }
        }
    }
}
