# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment: HeadofSecurityJumpsuit
  effects:
  - !type:GroupLoadoutEffect
    proto: MaleMoment

- type: startingGear
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment: HeadofSecurityJumpskirt
  effects:
  - !type:GroupLoadoutEffect
    proto: WomanMoment

- type: startingGear
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment: HeadofSecurityTurtleneck
  effects:
  - !type:GroupLoadoutEffect
    proto: MaleMoment

- type: startingGear
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment: HeadofSecurityTurtleneckSkirt
  effects:
  - !type:GroupLoadoutEffect
    proto: WomanMoment

- type: startingGear
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment: HeadofSecurityFormalSuit
  effects:
  - !type:GroupLoadoutEffect
    proto: MaleMoment

- type: startingGear
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment: HeadofSecurityFormalSkirt
  effects:
  - !type:GroupLoadoutEffect
    proto: WomanMoment

- type: startingGear
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment: HeadofSecurityHead

- type: startingGear
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment: HeadofSecurityBeret

- type: startingGear
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment: HeadofSecurityCloak

- type: startingGear
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment: HeadofSecurityMantle

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment: HeadofSecurityCoat

- type: startingGear
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment: HeadofSecurityWinterCoat

- type: startingGear
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS
