# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 72000 #20 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

#Sunrise-Start
- type: loadout
  id: HeadofSecurityJumpsuitHoSOld
  sponsorOnly: true
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSOld
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: HeadofSecurityJumpsuitUSSPBlack
  sponsorOnly: true
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSPBlack
#Sunrise-End

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

#Sunrise-Start
- type: loadout
  id: HeadofSecurityHatCap
  equipment:
    head: ClothingHeadHatCapHoS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: HeadofSecurityCapUSSPBlack
  sponsorOnly: true
  equipment:
    head: ClothingHeadHatCapUSSPBlack

- type: loadout
  id: HeadofSecurityCapLeather
  sponsorOnly: true
  equipment:
    head: ClothingHeadHatCapLeatherHoS
#Sunrise-End

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

- type: loadout
  id: HeadofSecurityCloakHOSCloak
  sponsorOnly: true
  equipment:
    neck: ClothingNeckCloakHOSCloak

- type: loadout
  id: HeadofSecurityDarthHOSCloak
  sponsorOnly: true
  equipment:
    neck: ClothingNeckCloakDarthHOSCloak
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

#Sunrise-Start
- type: loadout
  id: HeadofSecurityGreatcoat
  equipment:
    outerClothing: ClothingOuterCoatHoSGreatcoat
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: HeadofSecurityGreatcoatBlack
  sponsorOnly: true
  equipment:
    outerClothing: ClothingOuterCoatHOSOvercoatBlack
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: HeadofSecurityUSSPBlack
  sponsorOnly: true
  equipment:
    outerClothing: ClothingOuterCoatUSSPOvercoatBlack

- type: loadout
  id: HeadofSecurityOvercoat
  sponsorOnly: true
  equipment:
    outerClothing: ClothingOuterCoatHoSOvercoat
#Sunrise-End
