- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals
      shuttlePath: /Maps/_Sunrise/Shuttles/arrivals.yml # Sunrise-edit

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
# Sunrise-Edit
#    - type: StationCargoShuttle
#      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        mining: !type:GridSpawnGroup
          paths:
          - /Maps/_Sunrise/Shuttles/mining.yml # Sunrise-edit
          nameGrid: false
# Sunrise-Edit
#        trade: !type:GridSpawnGroup
#          addComponents:
#            - type: ProtectedGrid
#            - type: TradeStation
#          paths:
#            - /Maps/Shuttles/trading_outpost.yml
        # Spawn last
        satelite: !type:GridSpawnGroup
          minimumDistance: 300
          maximumDistance: 350
          minCount: 2
          maxCount: 2
          stationGrid: true
          paths:
          - /Maps/_Sunrise/Nonstations/telecom_satelite2.yml
          - /Maps/_Sunrise/Nonstations/telecom_satelite.yml
        ruins: !type:GridSpawnGroup
          hide: false # Sunrise-Edit
          nameGrid: true
          minCount: 8
          maxCount: 15
          stationGrid: false
          paths:
          - /Maps/Ruins/abandoned_outpost.yml
          - /Maps/Ruins/chunked_tcomms.yml
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          - /Maps/Ruins/djstation.yml
          - /Maps/Ruins/empty_flagship.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/syndicate_dropship.yml
          - /Maps/Ruins/whiteship_ancient.yml
          - /Maps/Ruins/whiteship_bluespacejumper.yml
          - /Maps/Ruins/wrecklaimer.yml
          - /Maps/_Sunrise/Ruins/abandoned_mining_outpost.yml
          - /Maps/_Sunrise/Ruins/abandoned_satelite.yml
          - /Maps/_Sunrise/Ruins/victory_mine.yml
          - /Maps/_Sunrise/Ruins/abandoned_lab.yml
          - /Maps/_Sunrise/Ruins/abandoned_syndi_lab.yml
        vgroid: !type:DungeonSpawnGroup
          minimumDistance: 300
          maximumDistance: 350
          nameDataset: NamesBorer
          stationGrid: false
          addComponents:
          - type: Gravity
            enabled: true
            inherent: true
          protos:
          - VGRoid

# Sunrise-Edit: Вынесено в _Sunrise
#- type: entity
#  id: BaseStationCentcomm
#  abstract: true
#  components:
#    - type: StationCentcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
