- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseRandomStation
  abstract: true
  components:
    - type: StationRandomTransform

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals
      shuttlePath: /Maps/_Sunrise/Shuttles/arrivals.yml # Sunrise-edit

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        trade:
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          paths:
            - /Maps/Shuttles/trading_outpost.yml
        mining:
          paths:
          - /Maps/_Sunrise/Shuttles/mining_shuttle.yml # Sunrise-edit
        # Spawn last
        ruins:
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          - /Maps/Ruins/djstation.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/relaystation.yml
          - /Maps/Ruins/syndicate_dropship.yml
          - /Maps/Ruins/whiteship_ancient.yml
          - /Maps/Ruins/whiteship_bluespacejumper.yml

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.

# Sunrise-start
- type: entity
  id: BaseCentCommShuttles
  abstract: true
  components:
  - type: GridSpawn
    groups:
      shuttles:
        addComponents:
        - type: CentCommShuttle
        paths:
        - /Maps/_Sunrise/Shuttles/centcom_shuttle.yml

- type: entity
  id: BaseStationCentComm
  abstract: true
  components:
  - type: StationCentComm
    station: SunriseCentComm
    shuttleWhitelist:
      components:
      - CentCommShuttle
      - ErtShuttle

- type: entity
  id: BaseStationImmortal
  abstract: true
  components:
  - type: StationImmortal

- type: entity
  id: BaseStationDontSelling
  abstract: true
  components:
  - type: StationDontSellingGrid

- type: entity
  id: BaseStationTransitHub
  abstract: true
  components:
  - type: StationTransitHub
    map: /Maps/_Sunrise/Nonstations/transit_hub.yml
    biomes:
    - Grasslands
    - LowDesert
    - Snow
# Sunrise-end
