- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsMagCombat
    id: CBURNPDA
    pocket1: PowerCellNanoTrasen  #sunrise-edit
    pocket2: WeaponLaserSvalinn #sunrise-edit
    belt: ClothingBeltBandolier
  storage:
    back:
    - WeaponShotgunPaladin12 #sunrise-edit
    - BoxShotgunIncendiary
    - BoxShotgunIncendiary  #sunrise-edit
    - BoxShotgunFlare  #sunrise-edit
    - ClusterBangFull #sunrise-edit
    - GrenadeIncendiary #sunrise-edit
    - PillAmbuzolPlus
    - SyringeAmbuzol  #sunrise-edit
    - MedkitCombatFilled  #sunrise-edit
