using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client._Sunrise.PlayerCache;
using Content.Client._Sunrise.Sheetlets;
using Content.Client.Interaction;
using Content.Client.Stylesheets;
using Content.Client.Items.Systems;
using Content.Client.Lobby;
using Content.Client.Stylesheets.Palette;
using Content.Client.Stylesheets.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Inventory.Controls;
using Content.Client.UserInterface.Systems.Storage.Controls;
using Content.Shared._Sunrise.Pets;
using Content.Shared._Sunrise.SponsorInventory;
using Content.Shared.Armor;
using Content.Shared.Clothing;
using Content.Shared.Clothing.Components;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Inventory;
using Content.Shared.Item;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Storage;
using Content.Shared.Storage.EntitySystems;
using Content.Shared.Whitelist;
using Content.Sunrise.Interfaces.Shared;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Containers;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.SponsorInventory;

/// <summary>
/// Lobby window for editing sponsor inventory items and pet selection on the selected character profile.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class InventoryWindow : DefaultWindow
{
    /*
     * Main lifecycle, profile selection, tab state, and job selection for the sponsor inventory window.
     */
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly PlayerCacheManager _playerCache = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private static readonly ProtoId<ItemSizePrototype> PocketableItemSize = "Small";
    private const string PlacementFilterAll = "";
    private const string PlacementFilterBag = "__bag";
    private const string PlacementFilterAnySlot = "__slot";
    private const string StorageTileEmptyTexturePath = "Storage/tile_empty";
    private const string StorageTileBlockedTexturePath = "Storage/tile_blocked";
    private const int BagTileSize = 32;

    // InventoryDisplay uses logical grid coordinates, so Sunrise-only slots get stable positions here instead of relying on prototype order.
    private static readonly Dictionary<string, Vector2i> LogicalSlotPositions = new()
    {
        ["head"] = new Vector2i(2, 0),
        ["eyes"] = new Vector2i(1, 0),

        ["neck"] = new Vector2i(1, 1),
        ["mask"] = new Vector2i(2, 1),
        ["ears"] = new Vector2i(3, 1),
        ["bra"] = new Vector2i(4, 1),

        ["jumpsuit"] = new Vector2i(1, 2),
        ["outerClothing"] = new Vector2i(2, 2),
        ["gloves"] = new Vector2i(3, 2),
        ["pants"] = new Vector2i(4, 2),

        ["shoes"] = new Vector2i(2, 3),
        ["socks"] = new Vector2i(4, 3),

        ["id"] = new Vector2i(0, 4),
        ["belt"] = new Vector2i(1, 4),
        ["back"] = new Vector2i(2, 4),
        ["pocket1"] = new Vector2i(3, 4),
        ["pocket2"] = new Vector2i(4, 4),
        ["suitstorage"] = new Vector2i(5, 4),

        ["pocket3"] = new Vector2i(3, 5),
        ["pocket4"] = new Vector2i(4, 5),
    };

    private readonly DragDropHelper<InventoryPaletteItemControl> _dragHelper;

    // OptionButton only reports integer ids, so these lists map UI ids back to job ids and placement filter values.
    private readonly List<string?> _jobOptions = new();
    private readonly List<string> _placementOptions = new();
    private readonly Dictionary<SlotControl, string> _slotControls = new();
    private readonly Dictionary<string, string> _slotLabels = new();
    private readonly Dictionary<EntityUid, string> _sponsorBagPreviewItems = new();
    private readonly List<InventoryPaletteEntry> _paletteEntries = new();

    private ISharedSponsorsManager? _sponsors;
    private SunriseInventorySystem _sponsorInventory = default!;
    private SharedContainerSystem _container = default!;
    private InventorySystem _inventory = default!;
    private SharedStorageSystem _storage = default!;
    private ItemSystem _item = default!;
    private SpriteSystem _sprite = default!;
    private EntityWhitelistSystem _whitelist = default!;

    // Edited data is cloned into the window first; SaveButton is the only path that publishes it back to the caller.
    private HumanoidCharacterProfile? _characterProfile;
    private SunriseInventoryProfile _editedInventoryProfile = new();
    private int? _characterSlot;
    private int _selectedJobOption;
    private int _sourceFilter;
    private int _placementFilter;
    private InventoryTab _selectedTab = InventoryTab.Equipment;
    private Direction _previewRotation = Direction.North;
    private EntityUid? _previewDummy;
    private EntityPrototypeView? _dragGhost;
    private string? _selectedEquipmentSlot;
    private bool _bagEditorOpen;
    private bool _externalSubscriptionsDetached;

    /// <summary>
    /// Raised with cloned character and sponsor inventory profiles when the user saves this window.
    /// </summary>
    public event Action<HumanoidCharacterProfile, int, SunriseInventoryProfile>? OnSaveRequested;

    /// <summary>
    /// Raised when the selected sponsor pet changes. Null clears the pet selection.
    /// </summary>
    public event Action<string?>? OnPetSelected;

    public InventoryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        IoCManager.Instance!.TryResolveType(out _sponsors);

        // These style classes are applied here because the panels are shared across tab and editor modes.
        ContentPanel.AddStyleClass(SunriseStyleClass.SponsorInventoryContentPanel);
        BagPanel.AddStyleClass(SunriseStyleClass.SponsorInventoryBagPanel);
        PalettePanel.AddStyleClass(SunriseStyleClass.SponsorInventoryPalettePanel);
        PaletteListPanel.AddStyleClass(SunriseStyleClass.SponsorInventoryPaletteListPanel);

        _sponsorInventory = _entManager.System<SunriseInventorySystem>();
        _container = _entManager.System<SharedContainerSystem>();
        _inventory = _entManager.System<InventorySystem>();
        _storage = _entManager.System<SharedStorageSystem>();
        _item = _entManager.System<ItemSystem>();
        _sprite = _entManager.System<SpriteSystem>();
        _whitelist = _entManager.System<EntityWhitelistSystem>();

        // DragDropHelper owns gesture timing; target resolution stays in this window because it depends on current tab state.
        _dragHelper = new DragDropHelper<InventoryPaletteItemControl>(OnBeginDrag, OnContinueDrag, OnEndDrag);

        SourceFilter.AddItem(Loc.GetString("sunrise-inventory-filter-all"), (int)InventoryPaletteSourceFilter.All);
        SourceFilter.AddItem(Loc.GetString("sunrise-inventory-filter-loadout"), (int)InventoryPaletteSourceFilter.Loadout);
        SourceFilter.AddItem(Loc.GetString("sunrise-inventory-filter-sponsor"), (int)InventoryPaletteSourceFilter.Sponsor);
        SourceFilter.SelectId((int)InventoryPaletteSourceFilter.All);
        SourceFilter.OnItemSelected += args =>
        {
            SourceFilter.SelectId(args.Id);
            _sourceFilter = args.Id;
            RefreshPalette();
        };
        PlacementFilter.OnItemSelected += args =>
        {
            PlacementFilter.SelectId(args.Id);
            _placementFilter = args.Id;
            var placement = CurrentPlacementFilter();
            _selectedEquipmentSlot = IsSpecificSlotFilter(placement)
                ? placement
                : null;
            RefreshSlotHighlights();
            RefreshPalette();
        };

        ItemSearch.OnTextChanged += _ => RefreshPalette();
        BagGridHost.MouseFilter = MouseFilterMode.Stop;

        // Changing jobs invalidates the preview dummy, slot layout, bag grid, and palette placement filters.
        JobOption.OnItemSelected += args =>
        {
            JobOption.SelectId(args.Id);
            _selectedJobOption = args.Id;
            RefreshSelectedTab();
        };

        SaveButton.OnPressed += _ =>
        {
            if (_characterProfile != null && _characterSlot != null)
                OnSaveRequested?.Invoke(_characterProfile.Clone(), _characterSlot.Value, _editedInventoryProfile.Clone());
        };

        LoadoutTabButton.OnPressed += _ => SelectTab(InventoryTab.Equipment);
        PetsTabButton.OnPressed += _ => SelectTab(InventoryTab.Pets);
        RotateLeftButton.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCw();
            SetPreviewRotation(_previewRotation);
        };
        RotateRightButton.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCcw();
            SetPreviewRotation(_previewRotation);
        };
        HideClothesButton.OnToggled += _ =>
        {
            UpdateHideClothesButtonText();
            RefreshPreviewClothingVisibility();
        };
        BagEditorButton.ToggleMode = true;
        BagEditorButton.OnPressed += _ =>
        {
            _bagEditorOpen = !_bagEditorOpen;
            if (_bagEditorOpen)
                _selectedEquipmentSlot = null;

            RefreshEquipment();
        };

        _playerCache.CacheChanged += RefreshPets;
        _sponsorInventory.InventoryDataChanged += OnInventoryDataChanged;

        if (_sponsors != null)
            _sponsors.LoadedSponsorInventoryConfig += OnSponsorInventoryConfigLoaded;

        LoadoutTabButton.Pressed = true;
    }

    /// <summary>
    /// Replaces the character and sponsor inventory profile currently edited by this window.
    /// </summary>
    public void SetProfile(HumanoidCharacterProfile? profile, int? characterSlot, SunriseInventoryProfile? sponsorInventory)
    {
        var previousJob = CurrentJobId;

        _characterProfile = profile?.Clone();
        _editedInventoryProfile = sponsorInventory?.Clone() ?? new SunriseInventoryProfile();
        _characterSlot = characterSlot;
        SaveButton.Disabled = _characterProfile == null || _characterSlot == null;
        ProfileName.Text = _characterProfile?.Name ?? Loc.GetString("sunrise-inventory-no-profile");

        // Keep the previously selected job when possible; otherwise fall back to the profile's preferred job order.
        BuildJobOptions(previousJob);
        RefreshSelectedTab();
    }

    /// <summary>
    /// Rebuilds the pet list from the currently cached sponsor data.
    /// </summary>
    public void RefreshPets()
    {
        PetsList.RemoveAllChildren();

        var currentPet = _playerCache.TryGetCachedPet(out var cachedPet) ? cachedPet : null;
        var localSession = _player.LocalSession;
        var availablePets = GetAvailablePets(localSession);

        // Pet selection is saved by the owning lobby/profile flow, so these buttons only raise a selection callback.
        var clearButton = new Button
        {
            Text = Loc.GetString("sunrise-inventory-pets-clear"),
            ToggleMode = true,
            Pressed = string.IsNullOrEmpty(currentPet),
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 5),
        };
        clearButton.OnPressed += _ => OnPetSelected?.Invoke(null);
        PetsList.AddChild(clearButton);

        foreach (var pet in _prototype.EnumeratePrototypes<PetSelectionPrototype>()
                     .OrderBy(p => p.LocalizedName))
        {
            var isAvailable = !pet.SponsorOnly || availablePets.Contains(pet.ID);
            var button = new Button
            {
                Text = pet.LocalizedName,
                ToggleMode = true,
                Pressed = pet.ID == currentPet,
                Disabled = !isAvailable,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 5),
            };

            button.OnPressed += _ =>
            {
                if (isAvailable)
                    OnPetSelected?.Invoke(pet.ID);
            };

            PetsList.AddChild(button);
        }
    }

    /// <summary>
    /// Detaches event handlers registered against managers and systems outside of the window tree.
    /// </summary>
    public void DetachExternalSubscriptions()
    {
        if (_externalSubscriptionsDetached)
            return;

        _externalSubscriptionsDetached = true;
        _playerCache.CacheChanged -= RefreshPets;
        _sponsorInventory.InventoryDataChanged -= OnInventoryDataChanged;
        ClearDragGhost();
        ClearPreviewDummy();

        if (_sponsors != null)
            _sponsors.LoadedSponsorInventoryConfig -= OnSponsorInventoryConfigLoaded;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _dragHelper.Update(args.DeltaSeconds);
    }

    private void OnSponsorInventoryConfigLoaded(SponsorInventoryConfig config)
    {
        RefreshEquipment();
    }

    private void OnInventoryDataChanged()
    {
        RefreshSelectedTab();
    }

    private void SelectTab(InventoryTab tab)
    {
        _selectedTab = tab;

        // Keep both button state and content visibility explicit; the buttons are not a built-in TabContainer.
        LoadoutTabButton.Pressed = tab == InventoryTab.Equipment;
        PetsTabButton.Pressed = tab == InventoryTab.Pets;

        EquipmentContent.Visible = tab == InventoryTab.Equipment;
        PetsContent.Visible = tab == InventoryTab.Pets;

        RefreshSelectedTab();
    }

    private void RefreshSelectedTab()
    {
        switch (_selectedTab)
        {
            case InventoryTab.Equipment:
                RefreshEquipment();
                break;
            case InventoryTab.Pets:
                RefreshPets();
                break;
        }
    }

    private void BuildJobOptions(string? previousJob)
    {
        JobOption.Clear();
        _jobOptions.Clear();

        foreach (var job in _prototype.EnumeratePrototypes<JobPrototype>()
                     .Where(j => j.SetPreference)
                     .OrderBy(j => j.LocalizedName))
        {
            AddJobOption(job.LocalizedName, job.ID);
        }

        // Option ids are dense list indices, so selectedJob must be resolved after the list has been rebuilt.
        var selectedJob = IsSelectableJob(previousJob)
            ? previousJob
            : GetPreferredProfileJob();

        _selectedJobOption = selectedJob == null
            ? -1
            : _jobOptions.IndexOf(selectedJob);

        if (_selectedJobOption < 0 && _jobOptions.Count > 0)
            _selectedJobOption = 0;

        if (_selectedJobOption >= 0)
            JobOption.SelectId(_selectedJobOption);
    }

    private void AddJobOption(string text, string? jobId)
    {
        var id = _jobOptions.Count;
        _jobOptions.Add(jobId);
        JobOption.AddItem(text, id);
    }

    private string? CurrentJobId
    {
        get
        {
            if (_selectedJobOption < 0 || _selectedJobOption >= _jobOptions.Count)
                return null;

            return _jobOptions[_selectedJobOption];
        }
    }

    private string? GetPreferredProfileJob()
    {
        if (_characterProfile == null)
            return null;

        foreach (var priority in new[] { JobPriority.High, JobPriority.Medium, JobPriority.Low })
        {
            foreach (var (jobId, jobPriority) in _characterProfile.JobPriorities)
            {
                if (jobPriority == priority && IsSelectableJob(jobId.Id))
                    return jobId.Id;
            }
        }

        var preferred = UserInterfaceManager.GetUIController<LobbyUIController>()
            .GetPreferredJob(_characterProfile)
            .ID;

        return IsSelectableJob(preferred)
            ? preferred
            : null;
    }

    private bool IsSelectableJob(string? jobId)
    {
        return !string.IsNullOrWhiteSpace(jobId) &&
               _jobOptions.Contains(jobId);
    }

}
