- type: entity
  id: CrateSecurityWebbing
  parent: CrateSecgear
  name: Security Webbing crate
  description: Contains two Security Webbing. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingBeltSecurityWebbing
        amount: 2
        
- type: entity
  id: CrateSecurityGlovesCombat
  parent: CrateSecgear
  name: Gloves Combat crate
  description: Contains three Gloves Combat. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingHandsGlovesCombat
        amount: 3

- type: entity
  id: CrateSecuritySWAT
  parent: CrateSecgear
  name: SWAT armor crate 
  description: Contains a SWAT kit. 2 heavy armor suit, 2 special forces helmet, 2special forces gas mask and 2 combat Swat boots. To open it, the Security Service access level is required.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorSWAT
        amount: 2
      - id: ClothingMaskGasSwat
        amount: 2
      - id: ClothingShoesSwat
        amount: 2
      - id: ClothingHeadHelmetSwat 
        amount: 2
      - id: ClothingHandsGlovesCombat
        amount: 2 