- type: entity
  id: BaseCentCommShuttles
  abstract: true
  components:
  - type: GridSpawn
    groups:
      shuttles:
        addComponents:
        - type: CentCommShuttle
        paths:
        - /Maps/_Sunrise/Shuttles/centcom_shuttle.yml

- type: entity
  id: BaseStationCentComm
  abstract: true
  components:
  - type: StationCentComm
    station: SunriseCentComm
    shuttleWhitelist:
      components:
      - CentCommShuttle
      - ErtShuttle

- type: entity
  id: BaseStationImmortal
  abstract: true
  components:
  - type: StationImmortal

- type: entity
  id: BaseStationDontSelling
  abstract: true
  components:
  - type: StationDontSellingGrid

- type: entity
  id: BaseStationTransitHub
  abstract: true
  components:
  - type: StationTransitHub
    map: /Maps/_Sunrise/Nonstations/transit_hub.yml
    biomes:
    - Grasslands
    - LowDesert
    - Snow

- type: entity
  id: BaseStationGoal
  abstract: true
  components:
  - type: StationGoal
    goals:
    - Shuttle
    - Singularity
    - SolarPanels
    - Artifacts
    - Bank
    - Zoo
    - MiningOutpost
    - Tesla
    - VirusZombie
