using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminWhoWindow : FancyWindow
    {
        private AdminWhoSystem? _adminWhoSystem;

        public AdminWhoWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            RefreshButton.OnPressed += _ => RefreshAdminList();
            CloseButton.OnPressed += _ => Close();
        }

        public void Initialize(AdminWhoSystem system)
        {
            _adminWhoSystem = system;
            _adminWhoSystem.OnAdminWhoUpdate += OnAdminListReceived;
        }

        public void Uninitialize()
        {
            if (_adminWhoSystem != null)
            {
                _adminWhoSystem.OnAdminWhoUpdate -= OnAdminListReceived;
                _adminWhoSystem = null;
            }
        }

        public void RefreshAdminList()
        {
            AdminsContainer.RemoveAllChildren();

            NoAdminsLabel.Visible = false;
            LoadingLabel.Visible = true;

            _adminWhoSystem?.RequestAdminWho();
        }

        private void OnAdminListReceived(List<AdminWhoEntry> admins)
        {
            LoadingLabel.Visible = false;

            if (admins.Count == 0)
            {
                NoAdminsLabel.Visible = true;
                return;
            }

            NoAdminsLabel.Visible = false;

            // Add each admin
            foreach (var admin in admins)
            {
                var adminText = new StringBuilder();
                adminText.Append(admin.Name);

                if (!string.IsNullOrEmpty(admin.Title))
                    adminText.Append($": [{admin.Title}]");

                if (admin.IsStealth)
                    adminText.Append(" (S)");

                if (admin.IsAfk)
                    adminText.Append(" [AFK]");

                var adminLabel = new Label
                {
                    Text = adminText.ToString(),
                    StyleClasses = { "LabelText" },
                    HorizontalAlignment = Control.HAlignment.Left,
                    Margin = new Thickness(16, 2, 8, 2)
                };
                AdminsContainer.AddChild(adminLabel);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Uninitialize();
            }
            base.Dispose(disposing);
        }
    }
}
