using Content.Client.Resources;
using Content.Client._Sunrise.UserInterface.CustomControls;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.RichText;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Threading;
using Content.Client._Sunrise.Messenger;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkPanel : BoxContainer
    {
        [Dependency] private readonly IUserInterfaceManager _ui = default!;

        private readonly Action<string> _messageSender;

        public int Unread { get; private set; } = 0;
        public DateTime LastMessage { get; private set; } = DateTime.MinValue;
        private List<string> PeopleTyping { get; set; } = new();
        public event Action<string>? InputTextChanged;

        // Sunrise-Start
        private static readonly Type[] TagsAllowed =
        [
            typeof(BoldItalicTag),
            typeof(BoldTag),
            typeof(BulletTag),
            typeof(ColorTag),
            typeof(HeadingTag),
            typeof(ItalicTag),
            typeof(EmojiTag)
        ];

        private DateTime? _lastDateHeader;
        public bool LoadDb { get; set; }
        private DateTime _cooldownEnd = DateTime.MinValue;
        private CancellationTokenSource? _cooldownCancellationTokenSource;
        private EmojiPickerWindow? _emojiPicker;
        // Sunrise-End

        public BwoinkPanel(Action<string> messageSender)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this); // Sunrise-Edit

            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            msg.AddText(Loc.GetString("bwoink-system-messages-being-relayed-to-discord"));
            msg.Pop();
            RelayedToDiscordLabel.SetMessage(msg);

            _messageSender = messageSender;

            OnVisibilityChanged += c =>
            {
                if (c.Visible)
                    Unread = 0;
            };
            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;

            // Sunrise-Start
            AdminWhoButton.OnPressed += _ =>
            {
                var ctrl = _ui.GetUIController<AdminWhoUIController>();
                ctrl.Toggle();
            };
            // Sunrise-End

            UpdateTypingIndicator();

            // Sunrise-Edit start - load texture for EmojiButton and hook up events
            var resourceCache = IoCManager.Resolve<IResourceCache>();
            var textureRect = new TextureRect
            {
                Texture = resourceCache.GetTexture("/Textures/_Sunrise/Interface/Smile.png"),
                SetWidth = 24,
                SetHeight = 24,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
            };
            EmojiButton.AddChild(textureRect);

            EmojiButton.OnPressed += _ =>
            {
                if (_emojiPicker != null && _emojiPicker.IsOpen)
                {
                    _emojiPicker.Close();
                    return;
                }

                _emojiPicker = new EmojiPickerWindow();
                _emojiPicker.OnEmojiSelected += emojiCode =>
                {
                    SenderLineEdit.Text += emojiCode;
                    SenderLineEdit.CursorPosition = SenderLineEdit.Text.Length;
                    SenderLineEdit.GrabKeyboardFocus();
                };

                _emojiPicker.OnClose += () => _emojiPicker = null;
                _emojiPicker.OpenCentered();
            };
            // Sunrise-Edit end
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text))
                return;

            // Check if we're still on cooldown
            if (DateTime.Now < _cooldownEnd)
                return;

            _messageSender.Invoke(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        {
            InputTextChanged?.Invoke(args.Text);
        }

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible && !message.DbLoad) // Sunrise-Edit
                Unread++;

            // Sunrise-Start
            if (_lastDateHeader == null || _lastDateHeader.Value.Date != message.SentAt.Date)
            {
                _lastDateHeader = message.SentAt.Date;

                var dateHeader = new FormattedMessage(1);
                dateHeader.AddMarkupOrThrow($"[center=\"{message.SentAt:dd.MM.yyyy}\"]");
                TextOutput.AddMessage(dateHeader);
            }
            // Sunrise-End

            var formatted = new FormattedMessage(1);
            var formattedTime = $"[bold]{message.SentAt:HH:mm}[/bold]";
            formatted.AddMarkupOrThrow($"{formattedTime} {message.Text}");
            TextOutput.AddMessage(formatted, TagsAllowed); // Sunrise-Edit
            if (!message.DbLoad) // Sunrise-Edit
                LastMessage = message.SentAt;
        }

        private void UpdateTypingIndicator()
        {
            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);

            var text = PeopleTyping.Count == 0
                ? string.Empty
                : Loc.GetString("bwoink-system-typing-indicator",
                    ("players", string.Join(", ", PeopleTyping)),
                    ("count", PeopleTyping.Count));

            msg.AddText(text);
            msg.Pop();

            TypingIndicator.SetMessage(msg);
        }

        public void UpdatePlayerTyping(string name, bool typing)
        {
            if (typing)
            {
                if (PeopleTyping.Contains(name))
                    return;

                PeopleTyping.Add(name);
                Robust.Shared.Timing.Timer.Spawn(TimeSpan.FromSeconds(10), () =>
                {
                    if (Disposed)
                        return;

                    PeopleTyping.Remove(name);
                    UpdateTypingIndicator();
                });
            }
            else
            {
                PeopleTyping.Remove(name);
            }

            UpdateTypingIndicator();
        }

        public void OnCooldownReceived(BwoinkCooldownMessage message)
        {
            // Set cooldown end time
            _cooldownEnd = DateTime.Now.Add(message.RemainingCooldown);

            // Disable input field and show feedback
            SenderLineEdit.Editable = false;
            SenderLineEdit.PlaceHolder = Loc.GetString("bwoink-cooldown-message",
                ("seconds", $"{message.RemainingCooldown.TotalSeconds:F1}"));

            // Clean up existing timer
            _cooldownCancellationTokenSource?.Cancel();
            _cooldownCancellationTokenSource = new CancellationTokenSource();

            // Set timer to re-enable input
            Robust.Shared.Timing.Timer.Spawn(message.RemainingCooldown, () =>
            {
                if (Disposed)
                    return;

                SenderLineEdit.Editable = true;
                SenderLineEdit.PlaceHolder = Loc.GetString("bwoink-input-placeholder");
            }, _cooldownCancellationTokenSource.Token);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            InputTextChanged = null;
            _cooldownCancellationTokenSource?.Cancel();
            _cooldownCancellationTokenSource = null;
        }
    }
}
