using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public Button CharacterSetupButton => CharacterSetup;

    public event Action? OnChangePetRequested;

    private EntityUid? _previewDummy;
    private EntityUid? _petPreviewDummy;
    private SpriteView? _characterSpriteView;
    private SpriteView? _petSpriteView;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ChangePetButton.OnPressed += _ => OnChangePetRequested?.Invoke();
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy);
        }

        _previewDummy = uid;

        // Удаляем старый спрайт персонажа
        if (_characterSpriteView != null)
        {
            ViewBox.RemoveChild(_characterSpriteView);
            _characterSpriteView = null;
        }

        _characterSpriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(4f, 4f),
            MaxSize = new Vector2(112, 112),
            Stretch = SpriteView.StretchMode.Fill,
        };
        _characterSpriteView.SetEntity(uid);
        ViewBox.AddChild(_characterSpriteView);
    }

    public void SetPetSprite(EntityUid? uid)
    {
        // Удаляем старый EntityUid питомца
        if (_petPreviewDummy != null)
        {
            if (uid == null || _petPreviewDummy != uid)
            {
                _entManager.DeleteEntity(_petPreviewDummy);
            }
        }

        _petPreviewDummy = uid;

        // Удаляем старый спрайт питомца
        if (_petSpriteView != null)
        {
            ViewBox.RemoveChild(_petSpriteView);
            _petSpriteView = null;
        }

        if (uid == null || !uid.Value.IsValid())
        {
            return;
        }

        _petSpriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(2f, 2f),
            MaxSize = new Vector2(80, 80),
            Stretch = SpriteView.StretchMode.Fill,
            VerticalAlignment = Control.VAlignment.Bottom,
        };
        _petSpriteView.SetEntity(uid.Value);
        ViewBox.AddChild(_petSpriteView);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(_previewDummy);
        _entManager.DeleteEntity(_petPreviewDummy);
        _previewDummy = null;
        _petPreviewDummy = null;
    }
}
