- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  displayWeight: 0
  special:
    - !type:AddImplantSpecial
      implants: [ TrackingImplant ]
    - !type:AddComponentSpecial
      components:
      - type: PlanetPrisoner

- type: startingGear
  id: PrisonerGear
  equipment:
    shoes: ClothingShoesBootsPrisonerGrey
    id: PrisonerPDA
    ears: ClothingHeadsetGrey
