using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Sunrise.ServersHub;

[GenerateTypedNameReferences]
public sealed partial class ServersHubEntry : PanelContainer
{
    private readonly Action<string>? _connectToServer;

    public ServersHubEntry(string serverTitle, int currentPlayerCount, int maxPlayerCount, string connectUrl, bool canConnect, Action<string>? connectToServer)
    {
        _connectToServer = connectToServer;
        RobustXamlLoader.Load(this);

        TitleLabel.Text = serverTitle;
        PlayersCountLabel.Text = $"{currentPlayerCount}/{maxPlayerCount}";

        ConnectButton.OnPressed += _ => ConnectToServer(connectUrl);
        ConnectButton.Text = canConnect ? Loc.GetString("serverhub-connect") : Loc.GetString("serverhub-here");
        // Банальная защита от дебила, ибо реконект к серверу на котором ты есть занимает столько же как и к другому.
        ConnectButton.Disabled = !canConnect;
    }

    private void ConnectToServer(string url) => _connectToServer?.Invoke(url);
}
