using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.ServersHub;

[GenerateTypedNameReferences]
public sealed partial class ServersHubUi : DefaultWindow
{
    public ServersHubUi()
    {
        RobustXamlLoader.Load(this);

        // Я не ебу что тут вообще еще должно быть, вся логика один хуй лежит внутри Control
    }

    public void RefreshHeader(int totalPlayers, int maxPlayers)
    {
        ServersHubHeaderLabel.Text = $"Сейчас играет: {totalPlayers}/{maxPlayers}";
    }
}
