using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Sunrise.ServersHub;
using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Sunrise.ServersHub
{
    [GenerateTypedNameReferences]
    public sealed partial class ServersHub : Control
    {
        [Dependency] private readonly IGameController _gameController = default!;
        [Dependency] private readonly ServersHubManager _serversHubManager = default!;

        private Action<string>? ConnectServer { get; set; }

        public ServersHub()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            _serversHubManager.ServersDataListChanged += RefreshServersList;

            ServersList.GenerateItem += GenerateButton;

            RefreshServersList(_serversHubManager.ServersDataList);

            ConnectServer += ConnectToServer;
        }

        private void ConnectToServer(string url)
        {
            // Почему-то данная хуйня всегда будет закрывать окно игры и открывать заново, даже если подключение идет
            // к серверу идентичного билда, почему нельзя было сделать метод редиала в этом же окне - загадка.
            // Я был рад поебать позги ПЖБ но мне кажется он опять пошлет меня нахуй.
            _gameController.Redial(url);
        }

        private void RefreshServersList(List<ServerHubEntry> servers)
        {
            var sortedServers = new List<ServerHubEntry>(servers);
            sortedServers.Sort(Compare);

            ServersList.PopulateList(sortedServers.Select(info => new ServerListData(info))
                .ToList());
        }

        private int Compare(ServerHubEntry x, ServerHubEntry y)
        {
            return y.CurrentPlayers.CompareTo(x.CurrentPlayers);
        }

        private void GenerateButton(ListData data, ListContainerButton button)
        {
            if (data is not ServerListData { Info: var info})
                return;

            var entry = new ServersHubEntry(info.Title, info.CurrentPlayers, info.MaxPlayers, info.ConnectUrl, info.CanConnect, ConnectServer);
            button.AddChild(entry);
            button.ToolTip = Loc.GetString("serverhub-info", ("mode", info.Preset), ("station", info.StationName));
            // Уменьшение задержки до милипиздрической ибо зумерки любят так быстро водить мышкой что чаще всего вообще
            // не знают что в игре существуют такие подсказки (Проверено на причинах блокировки ролей в лобби, они их
            // в лоб не видят)
            button.TooltipDelay = 0.1f;
        }
    }

    public record ServerListData(ServerHubEntry Info) : ListData;
}
