- type: entity
  name: explosive banana
  description: explosive banana
  parent: [FoodProduceBase, ItemHeftyBase]
  id: ExplosiveBanana
  components:
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: FlavorProfile
    flavors:
    - strange
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/explosive_banana.rsi
    state: produce
  - type: Produce
    seedId: ExplosiveBanana
  - type: SolutionContainerManager
    solutions:
      beaker:
        maxVol: 40
        canReact: false
      food:
        maxVol: 5
        canReact: false
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Potassium
          Quantity: 1
        - ReagentId: Water
          Quantity: 1
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: coffe arabica
  description: A coffe arabica grains, main food of scientist.
  parent: FoodProduceBase
  id: FoodCoffeeArabica
  components:
  - type: FlavorProfile
    flavors:
    - strange
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/coffee_arabica.rsi
    state: produce
  - type: Produce
    seedId: CoffeeArabica
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Grcoffee
          Quantity: 1
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: coffe robast
  description: A coffe robust grains, main food of shutcurity.
  parent: FoodProduceBase
  id: FoodCoffeeRobust
  components:
  - type: FlavorProfile
    flavors:
    - strange
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/coffee_robust.rsi
    state: produce
  - type: Produce
    seedId: CoffeeRobust
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Grcoffee
          Quantity: 2
        - ReagentId: Ephedrine
          Quantity: 1
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: geranium
  parent: FoodProduceBase
  id: FoodGeranium
  description: A flower with extracts often used in the production of medicine.
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: FlavorProfile
    flavors:
    - medicine
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 22
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Lacerinol
          Quantity: 20
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/geranium.rsi
  - type: Produce
    seedId: Geranium
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Geranium # TODO добавить теги цветка, когда оффы реализуют ЦветоМат и флористику

- type: entity
  name: glasscap
  description: Glass doesn't grow on trees! It grows on mushrooms, of course.
  id: GlassLog
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/glasscap.rsi
  - type: SolutionContainerManager
  - type: MeleeWeapon
    damage:
      types:
        Blunt: 10
  - type: Produce
    seedId: glasscap
  - type: Log
    spawnedPrototype: SheetGlass1
    spawnCount: 1

- type: entity
  name: plaststeelcap
  description: Plaststeel doesn't grow on trees! It grows on mushrooms, of course.
  id: PlastSteelLog
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/plaststeelcap.rsi
  - type: SolutionContainerManager
  - type: MeleeWeapon
    damage:
      types:
        Blunt: 12
  - type: Produce
    seedId: plaststeelcap
  - type: Log
    spawnedPrototype: SheetPlasteel1
    spawnCount: 1

- type: entity
  name: barrelmelon
  parent: FoodProduceBase
  id: FoodBarrelmelon
  description: Round brown object that you can slice and eat.
  components:
  - type: Item
    size: Small
  - type: FlavorProfile
    flavors:
    - barrelmelon
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 25
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Moonshine
          Quantity: 15
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/barrelmelon.rsi
  - type: Produce
    seedId: barrelmelon
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Moonshine
        Quantity: 20
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: SliceableFood
    count: 5
    slice: FoodBarrelmelonSlice
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: barrelmelon slice
  parent: ProduceSliceBase
  id: FoodBarrelmelonSlice
  description: Juicy green and brown slice.
  components:
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
    - barrelmelon
  - type: Sprite
    sprite: _Sunrise/Objects/Specific/Hydroponics/barrelmelon.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Moonshine
          Quantity: 3
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Moonshine
        Quantity: 4
  - type: Tag
    tags:
    - Fruit
    - Slice
