- type: antag
  id: GenericAntagonist
  name: roles-antag-generic-solo-antagonist-name
  antagonist: true
  objective: never-shown
  playTimeTracker: AntagAntagonist # Sunrise-Edit

- type: antag
  id: GenericTeamAntagonist
  name: roles-antag-generic-team-antagonist-name
  antagonist: true
  objective: never-shown
  playTimeTracker: AntagTeamAntagonist # Sunrise-Edit

- type: antag
  id: GenericFreeAgent
  name: roles-antag-generic-free-agent-name
  antagonist: true
  objective: never-shown
  playTimeTracker: AntagFreeAgent # Sunrise-Edit

- type: antag
  id: GenericSiliconAntagonist
  name: roles-antag-generic-silicon-antagonist-name
  antagonist: true
  objective: never-shown
  playTimeTracker: AntagSiliconAntagonist # Sunrise-Edit
