- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  setPreference: false
  playTimeTracker: AntagSubvertedSilicon # Sunrise-Edit
  objective: roles-antag-subverted-silicon-objective
