- type: antag
  id: Terminator
  name: roles-antag-terminator-name
  antagonist: true
  setPreference: false
  playTimeTracker: AntagTerminator # Sunrise-Edit
  objective: roles-antag-terminator-objective
