- type: antag
  id: Vampire
  name: roles-antag-vamire-name
  antagonist: true
  setPreference: true
  objective: roles-antag-vampire-description
#  guides: [ Changelings ]
  # Sunrise-Edit
  previewIcon:
    sprite: /Textures/_Sunrise/Interface/Misc/antag_preview.rsi
    state: vampire
