- type: antag
  id: MothershipCore
  name: roles-antag-mothership-core-name
  antagonist: true
  setPreference: true
  playTimeTracker: MothershipCore # Sunrise
  objective: roles-antag-mothership-core-objective
  requirements:
  # Sunrise-start
  - !type:DepartmentTimeRequirement
    department: Silicon
    time: 18000 # 5 hrs
  # Sunrise-end
  guides: [ Xenoborgs ]

- type: antag
  id: Xenoborg
  name: roles-antag-xenoborg-name
  antagonist: true
  setPreference: true
  playTimeTracker: Xenoborg # Sunrise
  objective: roles-antag-xenoborg-objective
  requirements:
  # Sunrise-start
  - !type:DepartmentTimeRequirement
    department: Silicon
    time: 18000 # 5 hrs
  # Sunrise-end
  guides: [ Xenoborgs ]
