using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.MentorHelp
{
    /// <summary>
    /// Mentor help window wrapper
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class MentorHelpWindow : DefaultWindow
    {
        public MentorHelpWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
