using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.MentorHelp
{
    /// <summary>
    /// Dialog for creating a new mentor help ticket
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class MentorHelpNewTicketDialog : DefaultWindow
    {
        public event Action<string, string>? OnTicketCreated;

        public MentorHelpNewTicketDialog()
        {
            RobustXamlLoader.Load(this);

            CancelButton.OnPressed += _ => Close();
            CreateButton.OnPressed += _ =>
            {
                var subject = SubjectInput.Text.Trim();
                var message = Rope.Collapse(MessageInput.TextRope).Trim();

                if (string.IsNullOrEmpty(subject))
                {
                    ErrorLabel.Text = Loc.GetString("mentor-help-new-ticket-error-subject");
                    ErrorLabel.Visible = true;
                    return;
                }

                if (string.IsNullOrEmpty(message))
                {
                    ErrorLabel.Text = Loc.GetString("mentor-help-new-ticket-error-message");
                    ErrorLabel.Visible = true;
                    return;
                }

                ErrorLabel.Visible = false;
                OnTicketCreated?.Invoke(subject, message);
            };
        }
    }
}
