using Content.Shared._Sunrise.MentorHelp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.MentorHelp
{
    [GenerateTypedNameReferences]
    public sealed partial class MentorHelpStatisticsDialog : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _loc = default!;

        private MentorHelpSystem? _mentorHelpSystem;

        public MentorHelpStatisticsDialog()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            StatisticsTabContainer.SetTabTitle(0, _loc.GetString("mentor-help-statistics-period-week"));
            StatisticsTabContainer.SetTabTitle(1, _loc.GetString("mentor-help-statistics-period-month"));
            StatisticsTabContainer.SetTabTitle(2, _loc.GetString("mentor-help-statistics-period-all-time"));

            CloseButton.OnPressed += _ => Close();
        }

        public void Initialize(MentorHelpSystem mentorHelpSystem)
        {
            if (_mentorHelpSystem != null)
                return;

            _mentorHelpSystem = mentorHelpSystem;
            _mentorHelpSystem.OnStatisticsReceived += OnStatisticsReceived;
            _mentorHelpSystem.OnTicketUpdated += OnTicketUpdated;
        }

        public void Uninitialize()
        {
            if (_mentorHelpSystem != null)
            {
                _mentorHelpSystem.OnStatisticsReceived -= OnStatisticsReceived;
                _mentorHelpSystem.OnTicketUpdated -= OnTicketUpdated;
                _mentorHelpSystem = null;
            }
        }

        private void OnTicketUpdated(object? sender, MentorHelpTicketUpdateMessage message)
        {
            if (!IsOpen)
                return;

            _mentorHelpSystem?.RequestStatistics();
        }

        private void OnStatisticsReceived(object? sender, MentorHelpStatisticsMessage message)
        {
            UpdateStatistics(WeekStatisticsContainer, message.WeekStatistics);
            UpdateStatistics(MonthStatisticsContainer, message.MonthStatistics);
            UpdateStatistics(AllTimeStatisticsContainer, message.AllTimeStatistics);
        }

        private void UpdateStatistics(BoxContainer container, List<MentorHelpStatisticsData> statistics)
        {
            container.RemoveAllChildren();

            if (statistics.Count == 0)
            {
                var noDataLabel = new Label
                {
                    Text = _loc.GetString("mentor-help-statistics-no-data"),
                    HorizontalAlignment = HAlignment.Center,
                    StyleClasses = { "LabelSubText" }
                };
                container.AddChild(noDataLabel);
                return;
            }

            foreach (var stat in statistics)
            {
                var entry = new StatisticsEntryControl();
                entry.UpdateData(stat);
                container.AddChild(entry);
            }
        }

        protected override void Opened()
        {
            base.Opened();
            _mentorHelpSystem?.RequestStatistics();
        }
    }
}
