using Content.Shared._Sunrise.MentorHelp;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.MentorHelp
{
    [GenerateTypedNameReferences]
    public sealed partial class StatisticsEntryControl : PanelContainer
    {
        private static readonly Color NormalColor = Color.FromHex("#202023");
        private static readonly Color HoverColor = Color.FromHex("#2F2F33");

        public StatisticsEntryControl()
        {
            RobustXamlLoader.Load(this);
            TooltipDelay = 0.5f;

            BackgroundColorPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = NormalColor
            };

            BackgroundColorPanel.OnMouseEntered += args =>
            {
                var panel = (StyleBoxFlat)BackgroundColorPanel.PanelOverride!;
                panel.BackgroundColor = HoverColor;
            };

            BackgroundColorPanel.OnMouseExited += args =>
            {
                var panel = (StyleBoxFlat)BackgroundColorPanel.PanelOverride!;
                panel.BackgroundColor = NormalColor;
            };
        }

        public void UpdateData(MentorHelpStatisticsData data)
        {
            MentorNameLabel.Text = data.MentorName;
            TicketsClaimedLabel.Text = data.TicketsClaimed.ToString();
            MessagesCountLabel.Text = data.MessagesCount.ToString();
        }
    }
}
