using System.Linq;
using Content.Client._Sunrise.Records;
using Content.Shared._Sunrise.Humanoid;
using Content.Shared._Sunrise.Records;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterRecordsTab : BoxContainer
{
    public event Action? OnRecordsChanged;

    private readonly IPrototypeManager _prototype;
    private readonly IRobustRandom _random;
    private readonly ILocalizationManager _loc;
    private readonly List<EducationEntryControls> _educationEntries = new();
    private bool _updating;
    private HumanoidCharacterProfile? _profile;
    private RecordsPreviewWindow? _previewWindow;

    public CharacterRecordsTab()
    {
        RobustXamlLoader.Load(this);
        _prototype = IoCManager.Resolve<IPrototypeManager>();
        _random = IoCManager.Resolve<IRobustRandom>();
        _loc = IoCManager.Resolve<ILocalizationManager>();

        RecordTabs.SetTabTitle(0, Loc.GetString("records-medical"));
        RecordTabs.SetTabTitle(1, Loc.GetString("records-security"));
        RecordTabs.SetTabTitle(2, Loc.GetString("records-employment"));

        Patronymic.OnTextChanged += _ => Changed();
        BirthDay.OnTextChanged   += _ => Changed();
        BirthMonth.OnTextChanged += _ => Changed();
        PreviewButton.OnPressed  += _ => OpenPreview();
        RandomizeAllButton.OnPressed += _ => RandomizeAllFields();

        PopulateEnumOptions(SecurityMaritalStatus, Enum.GetValues<RecordMaritalStatus>(), "records-marital");
        PopulateEnumOptions(EmploymentAcademicTitle, Enum.GetValues<RecordAcademicTitle>(), "records-academic-title-value");

        BindLineEdit(MedicalPostmortem, EmitMedical);
        BindLineEdit(MedicalEmergencyContact, EmitMedical);
        BindTextEdit(MedicalPhysiological, EmitMedical);
        BindTextEdit(MedicalPsychological, EmitMedical);
        BindTextEdit(MedicalNotes, EmitMedical);

        MedicalPostmortemDice.OnPressed += _ => { MedicalPostmortem.Text = RecordRandomTextGenerator.Postmortem(_random, _loc); EmitMedical(); };
        MedicalEmergencyContactDice.OnPressed += _ => { var (species, gender) = RelativeSpeciesGender(); MedicalEmergencyContact.Text = RecordRandomTextGenerator.EmergencyContact(_random, _loc, species, gender); EmitMedical(); };
        MedicalPhysiologicalDice.OnPressed += _ => { SetText(MedicalPhysiological, RecordRandomTextGenerator.Physiological(_random, _loc)); EmitMedical(); };
        MedicalPsychologicalDice.OnPressed += _ => { SetText(MedicalPsychological, RecordRandomTextGenerator.Psychological(_random, _loc)); EmitMedical(); };
        MedicalNotesDice.OnPressed += _ => { SetText(MedicalNotes, RecordRandomTextGenerator.Notes(_random, _loc)); EmitMedical(); };

        BindLineEdit(SecurityResidenceRegion, EmitSecurity);
        BindLineEdit(SecurityResidencePlanet, EmitSecurity);
        BindLineEdit(SecurityResidenceStreet, EmitSecurity);
        BindLineEdit(SecurityResidenceUnit, EmitSecurity);
        BindLineEdit(SecurityResidenceDetails, EmitSecurity);
        BindLineEdit(SecurityFeatures, EmitSecurity);
        BindLineEdit(SecurityRelatives, EmitSecurity);
        BindLineEdit(SecurityEmergencyContact, EmitSecurity);
        BindTextEdit(SecurityArrests, EmitSecurity);
        BindTextEdit(SecurityImprisonment, EmitSecurity);
        BindTextEdit(SecurityNotes, EmitSecurity);
        SecurityMaritalStatus.OnItemSelected += args =>
        {
            SecurityMaritalStatus.SelectId(args.Id);
            EmitSecurity();
        };
        SecuritySupervision.OnToggled += _ => EmitSecurity();

        SecurityResidenceRegionDice.OnPressed += _ => { SecurityResidenceRegion.Text = RecordRandomTextGenerator.ResidenceRegion(_random, _loc); EmitSecurity(); };
        SecurityResidencePlanetDice.OnPressed += _ => { SecurityResidencePlanet.Text = RecordRandomTextGenerator.ResidencePlanet(_random, _loc); EmitSecurity(); };
        SecurityResidenceStreetDice.OnPressed += _ => { SecurityResidenceStreet.Text = RecordRandomTextGenerator.ResidenceStreet(_random, _loc); EmitSecurity(); };
        SecurityResidenceUnitDice.OnPressed += _ => { SecurityResidenceUnit.Text = RecordRandomTextGenerator.ResidenceUnit(_random, _loc); EmitSecurity(); };
        SecurityResidenceDetailsDice.OnPressed += _ => { SecurityResidenceDetails.Text = RecordRandomTextGenerator.ResidenceDetails(_random, _loc); EmitSecurity(); };
        SecurityFeaturesDice.OnPressed += _ => { SecurityFeatures.Text = RecordRandomTextGenerator.IdentifyingFeatures(_random, _loc); EmitSecurity(); };
        SecurityRelativesDice.OnPressed += _ => { SecurityRelatives.Text = RecordRandomTextGenerator.CloseRelatives(_random, _loc); EmitSecurity(); };
        SecurityEmergencyContactDice.OnPressed += _ => { var (species, gender) = RelativeSpeciesGender(); SecurityEmergencyContact.Text = RecordRandomTextGenerator.EmergencyContact(_random, _loc, species, gender); EmitSecurity(); };
        SecurityArrestsDice.OnPressed += _ => { SetText(SecurityArrests, RecordRandomTextGenerator.ArrestHistory(_random, _loc)); EmitSecurity(); };
        SecurityImprisonmentDice.OnPressed += _ => { SetText(SecurityImprisonment, RecordRandomTextGenerator.ImprisonmentHistory(_random, _loc, HasArrestRecord())); EmitSecurity(); };
        SecurityNotesDice.OnPressed += _ => { SetText(SecurityNotes, RecordRandomTextGenerator.Notes(_random, _loc)); EmitSecurity(); };

        BindLineEdit(EmploymentAcademicTitleField, EmitEmployment);
        BindLineEdit(EmploymentAcademicTitleDate, EmitEmployment);
        BindTextEdit(EmploymentLicenses, EmitEmployment);
        BindTextEdit(EmploymentHistory, EmitEmployment);
        BindTextEdit(EmploymentNotes, EmitEmployment);
        EmploymentAcademicTitle.OnItemSelected += args =>
        {
            EmploymentAcademicTitle.SelectId(args.Id);
            UpdateAcademicTitleVisibility();
            EmitEmployment();
        };
        AddEducation.OnPressed += _ => AddEducationEntry(new EducationRecordData(), true);
        UpdateAcademicTitleVisibility();

        EmploymentAcademicTitleFieldDice.OnPressed += _ => { EmploymentAcademicTitleField.Text = RecordRandomTextGenerator.AcademicField(_random, _loc); EmitEmployment(); };
        EmploymentAcademicTitleDateDice.OnPressed += _ => { EmploymentAcademicTitleDate.Text = RecordRandomTextGenerator.Year(_random, _profile?.Age); EmitEmployment(); };
        EmploymentLicensesDice.OnPressed += _ => { SetText(EmploymentLicenses, RecordRandomTextGenerator.Licenses(_random, _loc)); EmitEmployment(); };
        EmploymentHistoryDice.OnPressed += _ => { SetText(EmploymentHistory, RecordRandomTextGenerator.EmploymentHistory(_random, _loc)); EmitEmployment(); };
        EmploymentNotesDice.OnPressed += _ => { SetText(EmploymentNotes, RecordRandomTextGenerator.Notes(_random, _loc)); EmitEmployment(); };
    }

    public string PatronymicValue
    {
        get => Patronymic.Text;
        set => Patronymic.Text = value;
    }

    public string BirthDayValue
    {
        get => BirthDay.Text;
        set => BirthDay.Text = value;
    }

    public string BirthMonthValue
    {
        get => BirthMonth.Text;
        set => BirthMonth.Text = value;
    }

    public void SetBirthYear(int year) => BirthYear.Text = year.ToString();

    /// <summary>
    /// Передаёт актуальный профиль редактора для построения корректного предпросмотра
    /// (вид, пол, возраст персонажа не хранятся в этой вкладке), а также обновляет
    /// доступные только для чтения рост и вес, взятые из показателей телосложения редактора.
    /// </summary>
    public void SetProfileContext(HumanoidCharacterProfile? profile)
    {
        _profile = profile;

        var species = profile != null && _prototype.TryIndex<SpeciesPrototype>(profile.Species, out var speciesPrototype)
            ? speciesPrototype
            : null;
        HeightValue.Text = profile == null
            ? _loc.GetString("records-value-no-data")
            : HumanoidBodyMetrics.FormatHeight(_loc, species, profile.Height);
        WeightValue.Text = profile == null
            ? _loc.GetString("records-value-no-data")
            : HumanoidBodyMetrics.FormatWeight(_loc, species, profile.Width, profile.Height);
    }

    public string MedicalRecordValue
    {
        get => StructuredCharacterRecords.WriteMedical(BuildMedical());
        set => SetMedical(StructuredCharacterRecords.ReadMedical(value));
    }

    public string SecurityRecordValue
    {
        get => StructuredCharacterRecords.WriteSecurity(BuildSecurity());
        set => SetSecurity(StructuredCharacterRecords.ReadSecurity(value));
    }

    public string EmploymentRecordValue
    {
        get => StructuredCharacterRecords.WriteEmployment(BuildEmployment());
        set => SetEmployment(StructuredCharacterRecords.ReadEmployment(value));
    }

    private void Changed()
    {
        if (!_updating)
            OnRecordsChanged?.Invoke();
    }

    private void SetMedical(MedicalRecordData record)
    {
        _updating = true;
        MedicalPostmortem.Text = record.PostmortemInstructions;
        MedicalEmergencyContact.Text = record.EmergencyContact;
        SetText(MedicalPhysiological, record.PhysiologicalNotes);
        SetText(MedicalPsychological, record.PsychologicalNotes);
        SetText(MedicalNotes, record.Notes);
        _updating = false;
    }

    private MedicalRecordData BuildMedical() => new()
    {
        PostmortemInstructions = MedicalPostmortem.Text,
        EmergencyContact = MedicalEmergencyContact.Text,
        PhysiologicalNotes = GetText(MedicalPhysiological),
        PsychologicalNotes = GetText(MedicalPsychological),
        Notes = GetText(MedicalNotes),
    };

    private void EmitMedical() => Changed();

    private void SetSecurity(SecurityRecordData record)
    {
        _updating = true;
        var residence = StructuredCharacterRecords.ReadResidence(record.Residence);
        SecurityResidenceRegion.Text = residence.Region;
        SecurityResidencePlanet.Text = residence.Planet;
        SecurityResidenceStreet.Text = residence.Street;
        SecurityResidenceUnit.Text = residence.Unit;
        SecurityResidenceDetails.Text = residence.Details;
        SecurityFeatures.Text = record.IdentifyingFeatures;
        SecurityMaritalStatus.SelectId((int) record.MaritalStatus);
        SecurityRelatives.Text = record.CloseRelatives;
        SecurityEmergencyContact.Text = record.EmergencyContact;
        SecuritySupervision.Pressed = record.UnderSecuritySupervision;
        SetText(SecurityArrests, record.ArrestHistory);
        SetText(SecurityImprisonment, record.ImprisonmentHistory);
        SetText(SecurityNotes, record.Notes);
        _updating = false;
    }

    private SecurityRecordData BuildSecurity() => new()
    {
        Residence = StructuredCharacterRecords.WriteResidence(new ResidenceRecordData
        {
            Region = SecurityResidenceRegion.Text,
            Planet = SecurityResidencePlanet.Text,
            Street = SecurityResidenceStreet.Text,
            Unit = SecurityResidenceUnit.Text,
            Details = SecurityResidenceDetails.Text,
        }),
        IdentifyingFeatures = SecurityFeatures.Text,
        MaritalStatus = (RecordMaritalStatus) SecurityMaritalStatus.SelectedId,
        CloseRelatives = SecurityRelatives.Text,
        EmergencyContact = SecurityEmergencyContact.Text,
        UnderSecuritySupervision = SecuritySupervision.Pressed,
        ArrestHistory = GetText(SecurityArrests),
        ImprisonmentHistory = GetText(SecurityImprisonment),
        Notes = GetText(SecurityNotes),
    };

    private void EmitSecurity() => Changed();

    // Персонаж контекста может быть не задан (окно открыто без профиля) — используем нейтральный вид/пол по умолчанию
    private (string Species, Gender Gender) RelativeSpeciesGender()
        => (_profile?.Species.Id ?? "Human", _profile?.Gender ?? Gender.Epicene);

    private void SetEmployment(EmploymentRecordData record)
    {
        _updating = true;
        foreach (var entry in _educationEntries)
            entry.Container.Orphan();
        _educationEntries.Clear();

        foreach (var education in record.Education)
            AddEducationEntry(education, false);

        EmploymentAcademicTitle.SelectId((int) record.AcademicTitle);
        EmploymentAcademicTitleField.Text = record.AcademicTitleField;
        EmploymentAcademicTitleDate.Text = record.AcademicTitleDate;
        SetText(EmploymentLicenses, record.Licenses);
        SetText(EmploymentHistory, record.EmploymentHistory);
        SetText(EmploymentNotes, record.Notes);
        UpdateAcademicTitleVisibility();
        UpdateEducationButton();
        _updating = false;
    }

    private EmploymentRecordData BuildEmployment()
    {
        var hasAcademicTitle = EmploymentAcademicTitle.SelectedId != (int) RecordAcademicTitle.NotApplicable;
        var record = new EmploymentRecordData
        {
            AcademicTitle = (RecordAcademicTitle) EmploymentAcademicTitle.SelectedId,
            AcademicTitleField = hasAcademicTitle ? EmploymentAcademicTitleField.Text : string.Empty,
            AcademicTitleDate = hasAcademicTitle ? EmploymentAcademicTitleDate.Text : string.Empty,
            Licenses = GetText(EmploymentLicenses),
            EmploymentHistory = GetText(EmploymentHistory),
            Notes = GetText(EmploymentNotes),
        };

        foreach (var entry in _educationEntries)
        {
            record.Education.Add(new EducationRecordData
            {
                Specialty = entry.Specialty.Text,
                Degree = (RecordAcademicDegree) entry.Degree.SelectedId,
                Institution = entry.Institution.Text,
                DiplomaDate = entry.DiplomaDate.Text,
            });
        }

        return record;
    }

    private void EmitEmployment() => Changed();

    /// <summary>
    /// Публичный метод — используется также при генерации полностью случайного персонажа
    /// (кнопка "Случайный персонаж"), чтобы досье не оставалось пустым.
    /// </summary>
    public void RandomizeAllFields()
    {
        RandomizeMedicalFields();
        RandomizeSecurityFields();
        RandomizeEmploymentFields();
    }

    private void RandomizeMedicalFields()
    {
        MedicalPostmortem.Text = RecordRandomTextGenerator.Postmortem(_random, _loc);
        MedicalEmergencyContact.Text = RecordRandomTextGenerator.EmergencyContact(_random, _loc, RelativeSpeciesGender().Species, RelativeSpeciesGender().Gender);
        SetText(MedicalPhysiological, RecordRandomTextGenerator.Physiological(_random, _loc));
        SetText(MedicalPsychological, RecordRandomTextGenerator.Psychological(_random, _loc));
        SetText(MedicalNotes, RecordRandomTextGenerator.Notes(_random, _loc));
        EmitMedical();
    }

    private void RandomizeSecurityFields()
    {
        SecurityResidenceRegion.Text = RecordRandomTextGenerator.ResidenceRegion(_random, _loc);
        SecurityResidencePlanet.Text = RecordRandomTextGenerator.ResidencePlanet(_random, _loc);
        SecurityResidenceStreet.Text = RecordRandomTextGenerator.ResidenceStreet(_random, _loc);
        SecurityResidenceUnit.Text = RecordRandomTextGenerator.ResidenceUnit(_random, _loc);
        SecurityResidenceDetails.Text = RecordRandomTextGenerator.ResidenceDetails(_random, _loc);
        SecurityFeatures.Text = RecordRandomTextGenerator.IdentifyingFeatures(_random, _loc);
        SecurityRelatives.Text = RecordRandomTextGenerator.CloseRelatives(_random, _loc);
        SecurityEmergencyContact.Text = RecordRandomTextGenerator.EmergencyContact(_random, _loc, RelativeSpeciesGender().Species, RelativeSpeciesGender().Gender);
        SetText(SecurityArrests, RecordRandomTextGenerator.ArrestHistory(_random, _loc));
        SetText(SecurityImprisonment, RecordRandomTextGenerator.ImprisonmentHistory(_random, _loc, HasArrestRecord()));
        SetText(SecurityNotes, RecordRandomTextGenerator.Notes(_random, _loc));
        EmitSecurity();
    }

    // Sunrise: заключение без ареста нелогично, поэтому дерево заключений разыгрывается
    // только если по текущему тексту "История арестов" видно, что задержания были
    private bool HasArrestRecord() => !RecordRandomTextGenerator.IsArrestRecordClean(_loc, GetText(SecurityArrests));

    private void RandomizeEmploymentFields()
    {
        EmploymentAcademicTitleField.Text = RecordRandomTextGenerator.AcademicField(_random, _loc);
        EmploymentAcademicTitleDate.Text = RecordRandomTextGenerator.Year(_random, _profile?.Age);
        SetText(EmploymentLicenses, RecordRandomTextGenerator.Licenses(_random, _loc));
        SetText(EmploymentHistory, RecordRandomTextGenerator.EmploymentHistory(_random, _loc));
        SetText(EmploymentNotes, RecordRandomTextGenerator.Notes(_random, _loc));

        foreach (var entry in _educationEntries)
        {
            entry.Specialty.Text = RecordRandomTextGenerator.Specialty(_random, _loc);
            entry.Institution.Text = RecordRandomTextGenerator.Institution(_random, _loc);
            entry.DiplomaDate.Text = RecordRandomTextGenerator.Year(_random, _profile?.Age);
        }

        EmitEmployment();
    }

    private void UpdateAcademicTitleVisibility()
    {
        var visible = EmploymentAcademicTitle.SelectedId != (int) RecordAcademicTitle.NotApplicable;
        AcademicTitleFieldLabel.Visible = visible;
        AcademicTitleFieldBox.Visible = visible;
        AcademicTitleDateLabel.Visible = visible;
        AcademicTitleDateBox.Visible = visible;
    }

    private void AddEducationEntry(EducationRecordData record, bool emit)
    {
        if (_educationEntries.Count >= StructuredCharacterRecords.MaxEducationEntries)
            return;

        var specialty = new LineEdit { Text = record.Specialty, HorizontalExpand = true, MinWidth = 180 };
        var specialtyDice = new Button { Text = Loc.GetString("records-randomize-field-button") };
        var degree = new OptionButton { HorizontalExpand = true, MinWidth = 180 };
        PopulateEnumOptions(degree, Enum.GetValues<RecordAcademicDegree>(), "records-degree");
        degree.SelectId((int) record.Degree);
        var institution = new LineEdit { Text = record.Institution, HorizontalExpand = true, MinWidth = 180 };
        var institutionDice = new Button { Text = Loc.GetString("records-randomize-field-button") };
        var diplomaDate = new LineEdit { Text = record.DiplomaDate, HorizontalExpand = true, MinWidth = 120 };
        var diplomaDateDice = new Button { Text = Loc.GetString("records-randomize-field-button") };
        var remove = new Button { Text = Loc.GetString("records-remove-education") };
        var title = new Label { StyleClasses = { "LabelSubText" } };

        var grid = new GridContainer { Columns = 2, HorizontalExpand = true };
        grid.AddChild(new Label { Text = Loc.GetString("records-specialty"), MinWidth = 150 });
        grid.AddChild(new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Children = { specialty, specialtyDice } });
        grid.AddChild(new Label { Text = Loc.GetString("records-degree"), MinWidth = 150 });
        grid.AddChild(degree);
        grid.AddChild(new Label { Text = Loc.GetString("records-institution"), MinWidth = 150 });
        grid.AddChild(new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Children = { institution, institutionDice } });
        grid.AddChild(new Label { Text = Loc.GetString("records-diploma-date"), MinWidth = 150 });
        grid.AddChild(new BoxContainer { Orientation = LayoutOrientation.Horizontal, HorizontalExpand = true, Children = { diplomaDate, diplomaDateDice } });

        var content = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Margin = new Thickness(8),
            Children = { title, grid, remove },
        };
        var container = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 2),
            StyleClasses = { "AngleRect" },
            Children = { content },
        };

        var controls = new EducationEntryControls(container, title, specialty, degree, institution, diplomaDate);
        _educationEntries.Add(controls);
        EducationEntries.AddChild(container);

        BindLineEdit(specialty, EmitEmployment);
        BindLineEdit(institution, EmitEmployment);
        BindLineEdit(diplomaDate, EmitEmployment);
        specialtyDice.OnPressed += _ => { specialty.Text = RecordRandomTextGenerator.Specialty(_random, _loc); EmitEmployment(); };
        institutionDice.OnPressed += _ => { institution.Text = RecordRandomTextGenerator.Institution(_random, _loc); EmitEmployment(); };
        diplomaDateDice.OnPressed += _ => { diplomaDate.Text = RecordRandomTextGenerator.Year(_random, _profile?.Age); EmitEmployment(); };
        degree.OnItemSelected += args =>
        {
            degree.SelectId(args.Id);
            EmitEmployment();
        };
        remove.OnPressed += _ =>
        {
            container.Orphan();
            _educationEntries.Remove(controls);
            RenumberEducationEntries();
            UpdateEducationButton();
            EmitEmployment();
        };

        RenumberEducationEntries();
        UpdateEducationButton();
        if (emit)
            EmitEmployment();
    }

    private void RenumberEducationEntries()
    {
        for (var i = 0; i < _educationEntries.Count; i++)
            _educationEntries[i].Title.Text = Loc.GetString("records-education-number", ("number", i + 1));
    }

    private void UpdateEducationButton()
    {
        AddEducation.Disabled = _educationEntries.Count >= StructuredCharacterRecords.MaxEducationEntries;
    }

    private void OpenPreview()
    {
        if (_previewWindow?.IsOpen == true)
        {
            _previewWindow.MoveToFront();
            return;
        }

        var loc = IoCManager.Resolve<ILocalizationManager>();
        var noData = loc.GetString("records-value-no-data");
        var identity = _profile == null
            ? new RecordIdentityData(string.Empty, string.Empty, string.Empty, string.Empty,
                noData, loc.GetString("records-date-of-birth-edit"),
                noData, noData, noData, noData, noData, noData)
            : RecordIdentityBuilder.FromProfile(_profile, _prototype, loc);

        _previewWindow = new RecordsPreviewWindow();
        _previewWindow.OnClose += () => _previewWindow = null;
        _previewWindow.SetRecords(
            RecordViewBuilder.Medical(identity, MedicalRecordValue, loc),
            RecordViewBuilder.Security(identity, SecurityRecordValue, loc),
            RecordViewBuilder.Employment(identity, EmploymentRecordValue, loc),
            RecordTabs.CurrentTab);
        _previewWindow.OpenCentered();
    }

    private void PopulateEnumOptions<T>(OptionButton button, IEnumerable<T> values, string keyPrefix) where T : struct, Enum
    {
        foreach (var value in values)
            button.AddItem(Loc.GetString($"{keyPrefix}-{value.ToString().ToLowerInvariant()}"), value.GetHashCode());
        button.SelectId(0);
    }

    private static void BindLineEdit(LineEdit edit, Action callback) => edit.OnTextChanged += _ => callback();
    private static void BindTextEdit(RecordTextEdit edit, Action callback) => edit.OnTextChanged += _ => callback();

    private static string GetText(RecordTextEdit edit) => Rope.Collapse(edit.TextRope).Trim();
    private static void SetText(RecordTextEdit edit, string value) => edit.TextRope = new Rope.Leaf(value);

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _previewWindow?.Close();
        _previewWindow = null;
    }

    private sealed record EducationEntryControls(
        PanelContainer Container,
        Label Title,
        LineEdit Specialty,
        OptionButton Degree,
        LineEdit Institution,
        LineEdit DiplomaDate);
}

