using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Antags.Vampires.UI;

[GenerateTypedNameReferences]
public sealed partial class VampireThrallMenu : FancyWindow
{
    public VampireThrallMenu()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Close();
    }
}
