using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.UserInterface.RichText;

[GenerateTypedNameReferences]
public sealed partial class TutorialKeybindControl : PanelContainer
{
    public TutorialKeybindControl()
    {
        RobustXamlLoader.Load(this);
    }
}
