using Content.Shared._Sunrise.CriminalRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.CriminalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class PrisonerRecordControl : Control
{
    private readonly IGameTiming _timing;
    private TimeSpan? _startTime;
    private int? _sentenceMinutes;
    private uint? _caseId;

    public Action? OnActionPressed;

    public PrisonerRecordControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _timing = IoCManager.Resolve<IGameTiming>();

        ActionButton.OnPressed += _ => OnActionPressed?.Invoke();

        MainPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#25252a"),
            BorderColor = Color.FromHex("#353540"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8
        };
    }

    public void SetupWaiting(PrisonerRecordInfo record)
    {
        NameLabel.Text = record.Name;
        _caseId = record.CaseId;
        InfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("prisoner-management-waiting-info", ("time", record.Sentence), ("case", record.CaseId))));
        ActionButton.Text = Loc.GetString("prisoner-management-start");
        ButtonContainer.Visible = true;
        _startTime = null;
    }

    public void SetupInProgress(IncarcerationInfo incar)
    {
        NameLabel.Text = incar.Name;
        _caseId = incar.CaseId;
        _startTime = incar.StartTime;
        _sentenceMinutes = incar.Sentence;
        _cellIndex = incar.CellIndex + 1;

        ButtonContainer.Visible = false;

        UpdateCountdown();
    }

    public void SetupFinished(PrisonerRecordInfo record)
    {
        NameLabel.Text = record.Name;
        _caseId = record.CaseId;
        InfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("prisoner-management-finished-info", ("case", record.CaseId))));
        ButtonContainer.Visible = false;
        _startTime = null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCountdown();
    }

    private void UpdateCountdown()
    {
        if (_startTime == null || _sentenceMinutes == null)
            return;

        var duration = TimeSpan.FromMinutes(_sentenceMinutes.Value);
        var elapsed = _timing.CurTime - _startTime.Value;
        var remaining = duration - elapsed;

        if (remaining < TimeSpan.Zero)
        {
            InfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
                Loc.GetString("prisoner-management-countdown-finished", ("case", _caseId ?? 0))));
            return;
        }

        string timeStr = $"{((int) remaining.TotalMinutes):D2}:{remaining.Seconds:D2}";
        InfoLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
            Loc.GetString("prisoner-management-countdown",
                ("cell", _cellIndex),
                ("time", timeStr),
                ("case", _caseId ?? 0))));
    }

    private int _cellIndex;

    public void SetCellIndex(int index)
    {
        _cellIndex = index + 1;
    }
}

