using System.Linq;
using Content.Shared._Sunrise.CriminalRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.CriminalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class PrisonerRecordControl : Control
{
    private readonly IGameTiming _timing;
    private TimeSpan? _startTime;
    private int? _sentenceMinutes;
    private uint? _caseId;

    private int _lastSeconds = -1;
    private bool _isCountdownFinished;
    private int _cellIndex;
    public int PermanentThreshold = 50;

    public Action? OnActionPressed;
    public Action? OnEscapePressed;
    public Action? OnParolePressed;

    public PrisonerRecordControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _timing = IoCManager.Resolve<IGameTiming>();

        ActionButton.OnPressed += _ => OnActionPressed?.Invoke();
        EscapeButton.OnPressed += _ => OnEscapePressed?.Invoke();
        ParoleButton.OnPressed += _ => OnParolePressed?.Invoke();
    }

    public void SetupWaiting(PrisonerRecordInfo record)
    {
        NameLabel.Text = record.Name;
        _caseId = record.CaseId;
        CaseLabel.Text = Loc.GetString("prisoner-management-case-id", ("case", record.CaseId));
        PositionLabel.Visible = false;
        TimeLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            record.IsWarning
                ? Loc.GetString("prisoner-management-warning")
                : Loc.GetString("prisoner-management-waiting-info", ("time", record.Sentence))));

        ActionButton.Text = Loc.GetString("prisoner-management-start");
        ActionButton.Visible = true;
        EscapeButton.Visible = false;
        ParoleButton.Visible = false;
        ButtonContainer.Visible = true;
        _startTime = null;
        _lastSeconds = -1;
        _isCountdownFinished = false;

        if (record.SentenceBreakdown != null && record.SentenceBreakdown.Count > 0)
            TimeLabel.ToolTip = FormatBreakdown(record.SentenceBreakdown);
    }

    public void SetupInProgress(IncarcerationInfo incar)
    {
        NameLabel.Text = incar.Name;
        _caseId = incar.CaseId;
        _startTime = incar.StartTime;
        _sentenceMinutes = incar.Sentence;

        CaseLabel.Text = Loc.GetString("prisoner-management-case-id", ("case", _caseId ?? 0));
        ButtonContainer.Visible = true;
        ActionButton.Visible = false;
        EscapeButton.Visible = true;
        ParoleButton.Visible = true;

        _lastSeconds = -1;
        _isCountdownFinished = false;

        if (_sentenceMinutes >= PermanentThreshold)
        {
            PositionLabel.Text = Loc.GetString("prisoner-management-permabrig");
            PositionLabel.Visible = true;
            TimeLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
                Loc.GetString("prisoner-management-permanent-info")));
            _startTime = null; // Disable timer updates
        }
        else
        {
            PositionLabel.Visible = true;
            UpdateCountdown();
        }
    }

    public void SetupFinished(PrisonerRecordInfo record)
    {
        NameLabel.Text = record.Name;
        _caseId = record.CaseId;
        CaseLabel.Text = Loc.GetString("prisoner-management-case-id", ("case", record.CaseId));
        PositionLabel.Visible = false;
        TimeLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            record.IsWarning
                ? Loc.GetString("prisoner-management-warning")
                : Loc.GetString(record.IsParoled ? "prisoner-management-paroled-info" : "prisoner-management-finished-info")));

        ButtonContainer.Visible = false;
        _startTime = null;
        _lastSeconds = -1;
        _isCountdownFinished = false;

        if (record.SentenceBreakdown != null && record.SentenceBreakdown.Count > 0)
            TimeLabel.ToolTip = FormatBreakdown(record.SentenceBreakdown);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCountdown();
    }

    private void UpdateCountdown()
    {
        if (_startTime == null || _sentenceMinutes == null)
            return;

        var duration = TimeSpan.FromMinutes(_sentenceMinutes.Value);
        var elapsed = _timing.CurTime - _startTime.Value;
        var remaining = duration - elapsed;

        if (remaining < TimeSpan.Zero)
        {
            if (!_isCountdownFinished)
            {
                TimeLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
                    Loc.GetString("prisoner-management-countdown-finished")));
                _isCountdownFinished = true;
                _lastSeconds = -1;
            }
            return;
        }

        var totalSeconds = (int) remaining.TotalSeconds;
        PositionLabel.Text = Loc.GetString("prisoner-management-cell-name", ("cell", _cellIndex));

        if (totalSeconds == _lastSeconds)
            return;

        _lastSeconds = totalSeconds;
        _isCountdownFinished = false;

        string timeStr = $"{((int) remaining.TotalMinutes):D2}:{remaining.Seconds:D2}";
        TimeLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("prisoner-management-countdown", ("time", timeStr))));
    }

    public void SetCellIndex(int index)
    {
        _cellIndex = index + 1;
    }

    private string FormatBreakdown(List<SentenceBreakdownEntry> entries)
    {
        var lines = new List<string>();
        foreach (var entry in entries)
        {
            if (entry.Args != null)
            {
                var args = entry.Args.Select(x => (x.Key, x.Value)).ToArray();
                lines.Add(Loc.GetString(entry.LocId, args));
            }
            else
            {
                lines.Add(Loc.GetString(entry.LocId));
            }
        }
        return string.Join("\n", lines);
    }
}

