using Content.Shared._Sunrise.CriminalRecords;
using Content.Shared._Sunrise.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Sunrise.CriminalRecords.UI;

// --- Case Item Control ---
[GenerateTypedNameReferences]
public sealed partial class SunriseCriminalRecordsCaseControl : Button
{
    public Action<CriminalCase>? OnEdit;

    public SunriseCriminalRecordsCaseControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Setup(
        CriminalCase @case,
        IPrototypeManager proto,
        List<ProtoId<CorporateLawSectionPrototype>> articles,
        int threshold)
    {
        CaseIdLabel.Text = $"#{@case.Id}";

        var statusLoc = @case.Status switch
        {
            CriminalCaseStatus.Open => "sunrise-records-status-open",
            CriminalCaseStatus.Incarcerated => "sunrise-records-status-incarcerated",
            CriminalCaseStatus.Finished => "sunrise-records-status-finished",
            CriminalCaseStatus.Closed => "sunrise-records-status-closed",
            _ => "unknown"
        };
        StatusLabel.Text = Loc.GetString(statusLoc).ToUpperInvariant();

        var statusColor = @case.Status switch
        {
            CriminalCaseStatus.Open => Color.FromHex("#ff4444"),
            CriminalCaseStatus.Incarcerated => Color.FromHex("#ffbb33"),
            CriminalCaseStatus.Finished => Color.FromHex("#00C851"),
            _ => Color.FromHex("#aaaaaa")
        };
        StatusLabel.FontColorOverride = statusColor;

        // --- Laws & Colors ---
        var msg = new FormattedMessage();
        Color? primaryColor = null;

        for (var i = 0; i < @case.Laws.Count; i++)
        {
            var id = @case.Laws[i];
            if (!proto.TryIndex(id, out var law))
                continue;

            var color = Color.White;
            foreach (var sectionId in articles)
            {
                if (proto.TryIndex(sectionId, out var section) && section.Entries.Contains(id))
                {
                    color = section.Color ?? Color.White;
                    break;
                }
            }

            if (primaryColor == null && law.Category == LawCategory.Article)
                primaryColor = color;

            var identifier = !string.IsNullOrEmpty(law.LawIdentifier) ? law.LawIdentifier : Loc.GetString(law.Title);
            msg.PushColor(color);
            msg.AddText(identifier);
            msg.Pop();

            if (i < @case.Laws.Count - 1)
                msg.AddText(", ");
        }
        LawsRichLabel.SetMessage(msg);

        // Strip Color
        LateralStrip.PanelOverride = new StyleBoxFlat { BackgroundColor = primaryColor ?? Color.FromHex("#25252a") };

        // --- Circumstances ---
        float mitigationTotal = 1.0f;
        float aggravationTotal = 1.0f;

        foreach (var circId in @case.Circumstances)
        {
            if (!proto.TryIndex<CorporateLawPrototype>(circId, out var circ))
                continue;

            if (circ.SentenceMultiplier < 1.0f)
                mitigationTotal *= circ.SentenceMultiplier;
            else if (circ.SentenceMultiplier > 1.0f)
                aggravationTotal *= circ.SentenceMultiplier;
        }

        if (mitigationTotal < 1.0f)
        {
            var percent = (int) Math.Round((1.0f - mitigationTotal) * 100);
            MitigatingPercentLabel.Text = Loc.GetString("sunrise-records-mitigating-summary", ("percent", (object) percent));
            MitigatingPercentLabel.Visible = true;
            MitigatingPercentLabel.FontColorOverride = Color.FromHex("#00ffff");
        }
        else
            MitigatingPercentLabel.Visible = false;

        if (aggravationTotal > 1.0f)
        {
            var percent = (int) Math.Round((aggravationTotal - 1.0f) * 100);
            AggravatingPercentLabel.Text = Loc.GetString("sunrise-records-aggravating-summary", ("percent", (object) percent));
            AggravatingPercentLabel.Visible = true;
            AggravatingPercentLabel.FontColorOverride = Color.FromHex("#ff4444");
        }
        else
            AggravatingPercentLabel.Visible = false;

        // --- Sentence ---
        var total = @case.CalculatedSentence;

        if (total >= threshold)
        {
            SentenceValueLabel.Text = Loc.GetString("sunrise-records-sentence-life").ToUpperInvariant();
            SentenceValueLabel.FontColorOverride = Color.Red;
        }
        else
        {
            SentenceValueLabel.Text = Loc.GetString("sunrise-records-sentence-total-short", ("total", (object) total)).ToUpperInvariant();
            SentenceValueLabel.FontColorOverride = Color.White;
        }
        SentenceContainer.Visible = true;

        OnPressed += _ => OnEdit?.Invoke(@case);
    }
}

// --- Case List Fragment ---
[GenerateTypedNameReferences]
public sealed partial class SunriseCriminalRecordsCaseList : Control
{
    public Action? OnCreateCase;
    public Action<CriminalCase>? OnEditCase;

    public SunriseCriminalRecordsCaseList()
    {
        RobustXamlLoader.Load(this);

        VerticalExpand = true;
        HorizontalExpand = true;

        CreateCaseButton.OnPressed += _ => OnCreateCase?.Invoke();
    }

    public void Populate(
        List<CriminalCase> cases,
        IPrototypeManager proto,
        List<ProtoId<CorporateLawSectionPrototype>> articles,
        int threshold)
    {
        CasesContainer.DisposeAllChildren();
        foreach (var @case in cases)
        {
            var control = new SunriseCriminalRecordsCaseControl();
            control.Setup(@case, proto, articles, threshold);
            control.OnEdit += c => OnEditCase?.Invoke(c);
            CasesContainer.AddChild(control);
        }
    }
}
