using System.Linq;
using Content.Shared._Sunrise.Laws;
using Content.Shared._Sunrise.CriminalRecords;
using Content.Shared._Sunrise.CriminalRecords.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared._Sunrise.Laws.Systems;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Timing;
using Content.Shared.Station;

namespace Content.Client._Sunrise.CriminalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class SunriseCriminalRecordsCaseEditor : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private readonly SharedSunriseCriminalRecordsSystem _recordsSystem;
    private readonly SharedStationCorporateLawSystem _stationLaw;

    public EntityUid? ConsoleEntity;

    public Action<uint, List<ProtoId<CorporateLawPrototype>>, List<ProtoId<CorporateLawPrototype>>, string>? OnSave;

    public Action? OnFinalize;
    public Action? OnBack;

    private List<ProtoId<CorporateLawPrototype>> _currentLaws = new();
    private List<ProtoId<CorporateLawPrototype>> _currentCircumstances = new();
    private bool _isReadOnly;
    private CriminalCaseStatus? _lastStatus;

    private List<CriminalCase> _allCases = new();
    private uint? _lastCaseId;
    private int _savedSentence;

    private float _saveTimer;
    private const float SaveDelay = 1.0f;
    private bool _dirty;

    public SunriseCriminalRecordsCaseEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _recordsSystem = _ent.System<SharedSunriseCriminalRecordsSystem>();
        _stationLaw = _ent.System<SharedStationCorporateLawSystem>();

        VerticalExpand = true;
        HorizontalExpand = true;

        FinalizeButton.OnPressed += _ => OnFinalize?.Invoke();
        BackButton.OnPressed += _ => OnBack?.Invoke();

        NotesInput.Placeholder = new Rope.Leaf(Loc.GetString("sunrise-records-notes-placeholder"));
        NotesInput.OnTextChanged += _ =>
        {
            _dirty = true;
            _saveTimer = SaveDelay;
        };
    }

    public void Setup(CriminalCase @case, List<CriminalCase> allCases)
    {
        _savedSentence = @case.CalculatedSentence;
        bool isStatusChanged = _lastStatus != @case.Status;
        bool isSameCase = _lastCaseId == @case.Id;
        _lastCaseId = @case.Id;
        _lastStatus = @case.Status;
        _allCases = allCases;
        _isReadOnly = @case.Status != CriminalCaseStatus.Open;

        EditorHeader.Text = Loc.GetString("sunrise-records-editor-header", ("id", @case.Id));

        var notes = @case.Notes ?? "";
        if (!isSameCase || (Rope.Collapse(NotesInput.TextRope) != notes && !NotesInput.HasKeyboardFocus()))
        {
            NotesInput.TextRope = new Rope.Leaf(notes);
            _dirty = false;
        }

        NotesInput.Editable = !_isReadOnly;
        FinalizeButton.Disabled = _isReadOnly;

        if (isSameCase && !isStatusChanged)
        {
            UpdateSentenceDisplay();
            return;
        }

        // Only sync collections if it's a different case or status changed
        _currentLaws = new List<ProtoId<CorporateLawPrototype>>(@case.Laws);
        _currentCircumstances = new List<ProtoId<CorporateLawPrototype>>(@case.Circumstances);

        PopulateLaws();
    }

    public void SetupNew()
    {
        _lastCaseId = null;
        _currentLaws.Clear();
        _currentCircumstances.Clear();
        _allCases.Clear();
        _isReadOnly = false;

        EditorHeader.Text = "";
        NotesInput.TextRope = Rope.Leaf.Empty;
        NotesInput.Editable = true;
        FinalizeButton.Disabled = true;

        PopulateLaws();
    }

    private void Save()
    {
        if (_isReadOnly || _lastCaseId == null) return;
        var notes = Rope.Collapse(NotesInput.TextRope);
        OnSave?.Invoke((uint) _lastCaseId.Value, new List<ProtoId<CorporateLawPrototype>>(_currentLaws), new List<ProtoId<CorporateLawPrototype>>(_currentCircumstances), notes);
        _dirty = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_dirty) return;

        _saveTimer -= args.DeltaSeconds;
        if (_saveTimer <= 0)
        {
            Save();
        }
    }

    private void PopulateLaws()
    {
        MainEditorPanel.Visible = !_isReadOnly;
        ReadOnlyContent.Visible = _isReadOnly;

        LawsContainer.DisposeAllChildren();
        MitigatingContainer.DisposeAllChildren();
        AggravatingContainer.DisposeAllChildren();
        ReadOnlyList.DisposeAllChildren();

        List<ProtoId<CorporateLawSectionPrototype>> articles;
        List<ProtoId<CorporateLawPrototype>> circumstances;

        _stationLaw.GetEffectiveLawset(ConsoleEntity, out _, out articles, out circumstances, out _);

        if (_isReadOnly)
            PopulateReadOnly(articles);
        else
            PopulateEditable(circumstances, articles);

        UpdateSentenceDisplay();
    }

    private void PopulateReadOnly(
        List<ProtoId<CorporateLawSectionPrototype>> articles)
    {
        ReadOnlyContent.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#0a0a0f"),
            BorderColor = Color.FromHex("#15151a"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 12,
            ContentMarginRightOverride = 12,
            ContentMarginTopOverride = 12,
            ContentMarginBottomOverride = 12
        };

        // Group laws by category for visual consistency
        var selectedLaws = _currentLaws
            .Select(id => _proto.TryIndex(id, out var law) ? law : null)
            .Where(l => l != null)
            .Cast<CorporateLawPrototype>()
            .OrderBy(l => l.LawIdentifier ?? "")
            .ToList();

        if (selectedLaws.Count > 0)
        {
            ReadOnlyList.AddChild(new Label { Text = Loc.GetString("sunrise-records-select-laws"), StyleClasses = { "LabelHeading" }, Margin = new Thickness(0, 4) });
            ReadOnlyList.AddChild(new PanelContainer { StyleClasses = { "LowDivider" }, MinHeight = 1, Margin = new Thickness(0, 0, 0, 4) });

            foreach (var law in selectedLaws)
            {
                var catColor = GetSectionColor(law.ID, articles);
                AddLawEntry(law, ReadOnlyList, _currentLaws, catColor);
            }
        }
        else
        {
            ReadOnlyList.AddChild(new Label { Text = Loc.GetString("sunrise-records-no-laws"), StyleClasses = { "LabelSecondaryColor" }, Margin = new Thickness(12, 0) });
        }

        // Circumstances
        if (_currentCircumstances.Count > 0)
        {
            ReadOnlyList.AddChild(new Label { Text = Loc.GetString("sunrise-records-select-circumstances"), StyleClasses = { "LabelHeading" }, Margin = new Thickness(0, 12, 0, 4) });
            ReadOnlyList.AddChild(new PanelContainer { StyleClasses = { "LowDivider" }, MinHeight = 1, Margin = new Thickness(0, 0, 0, 4) });

            foreach (var circId in _currentCircumstances)
            {
                if (!_proto.TryIndex(circId, out var law)) continue;

                Color circColor = law.Category == LawCategory.Mitigating ? Color.FromHex("#00ffff") : Color.FromHex("#dc143c");
                AddLawEntry(law, ReadOnlyList, _currentCircumstances, circColor);
            }
        }
    }

    private void PopulateEditable(
        List<ProtoId<CorporateLawPrototype>> circumstances,
        List<ProtoId<CorporateLawSectionPrototype>> articles)
    {
        MainEditorPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#0a0a0f"),
            BorderColor = Color.FromHex("#15151a"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 12,
            ContentMarginRightOverride = 12,
            ContentMarginTopOverride = 12,
            ContentMarginBottomOverride = 12
        };

        NotesPanel.PanelOverride = MainEditorPanel.PanelOverride;

        // Provisions are informative and shouldn't be selectable as 'broken' articles.
        // We skip populating them here to avoid confusion.

        // Populate Articles in Collapsibles
        foreach (var sectionId in articles)
        {
            if (!_proto.TryIndex(sectionId, out var section))
                continue;

            var body = new CollapsibleBody { HorizontalExpand = true };
            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 12,
                Margin = new Thickness(8, 12, 8, 12)
            };
            body.AddChild(content);

            bool anySelected = false;

            var heading = new CollapsibleHeading(Loc.GetString(section.Title));
            heading.MinHeight = 24;
            heading.Label.StyleClasses.Add("LabelHeadingBold");

            var catColor = GetSectionColor(sectionId);
            heading.Label.FontColorOverride = catColor;

            var sectionCatStyle = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1a1a1e").WithAlpha(0.8f),
                BorderColor = catColor.WithAlpha(0.3f),
                BorderThickness = new Thickness(1)
            };

            var collapsible = new Collapsible(heading, body);

            var sectionPanel = new PanelContainer { PanelOverride = sectionCatStyle, Margin = new Thickness(0, 0, 0, 1) };
            sectionPanel.AddChild(collapsible);
            LawsContainer.AddChild(sectionPanel);

            foreach (var entryId in section.Entries)
            {
                if (!_proto.TryIndex(entryId, out var law))
                    continue;
                AddLawEntry(law, content, _currentLaws, catColor);
                if (_currentLaws.Contains(law.ID))
                    anySelected = true;
            }

            collapsible.BodyVisible = anySelected;
        }

        // Populate Mitigating Circumstances in Collapsible
        var mitigatingBody = new CollapsibleBody { HorizontalExpand = true };
        var mitigatingContent = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 1, Margin = new Thickness(8, 0, 8, 4) };
        mitigatingBody.AddChild(mitigatingContent);

        var mitColor = Color.FromHex("#00ffff");
        var mitigatingHeading = new CollapsibleHeading(Loc.GetString("sunrise-records-mitigating-circumstances"));
        mitigatingHeading.Label.FontColorOverride = mitColor;
        mitigatingHeading.Label.StyleClasses.Add("LabelHeadingBold");
        mitigatingHeading.MinHeight = 24;

        var mitStyle = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1a1a1e"), BorderColor = mitColor.WithAlpha(0.2f), BorderThickness = new Thickness(1) };
        var mitigatingCollapsible = new Collapsible(mitigatingHeading, mitigatingBody);
        var mitigatingPanel = new PanelContainer { PanelOverride = mitStyle, Margin = new Thickness(0, 1) };
        mitigatingPanel.AddChild(mitigatingCollapsible);

        // Populate Aggravating Circumstances in Collapsible
        var aggravatingBody = new CollapsibleBody { HorizontalExpand = true };
        var aggravatingContent = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 1, Margin = new Thickness(8, 0, 8, 4) };
        aggravatingBody.AddChild(aggravatingContent);

        var aggColor = Color.FromHex("#dc143c");
        var aggravatingHeading = new CollapsibleHeading(Loc.GetString("sunrise-records-aggravating-circumstances"));
        aggravatingHeading.Label.FontColorOverride = aggColor;
        aggravatingHeading.Label.StyleClasses.Add("LabelHeadingBold");
        aggravatingHeading.MinHeight = 24;

        var aggStyle = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1a1a1e"), BorderColor = aggColor.WithAlpha(0.2f), BorderThickness = new Thickness(1) };
        var aggravatingCollapsible = new Collapsible(aggravatingHeading, aggravatingBody);
        var aggravatingPanel = new PanelContainer { PanelOverride = aggStyle, Margin = new Thickness(0, 1) };
        aggravatingPanel.AddChild(aggravatingCollapsible);

        bool anyMitigating = false;
        bool anyAggravating = false;

        foreach (var entryId in circumstances)
        {
            if (!_proto.TryIndex(entryId, out var law))
                continue;

            if (law.Category == LawCategory.Provision)
                continue;

            if (law.Category == LawCategory.Mitigating)
            {
                AddLawEntry(law, mitigatingContent, _currentCircumstances, mitColor);
                if (_currentCircumstances.Contains(law.ID))
                    anyMitigating = true;
            }
            else if (law.Category == LawCategory.Aggravating)
            {
                AddLawEntry(law, aggravatingContent, _currentCircumstances, aggColor);
                if (_currentCircumstances.Contains(law.ID))
                    anyAggravating = true;
            }
        }

        mitigatingCollapsible.BodyVisible = anyMitigating;
        aggravatingCollapsible.BodyVisible = anyAggravating;

        MitigatingContainer.AddChild(mitigatingPanel);
        AggravatingContainer.AddChild(aggravatingPanel);
    }

    private void AddLawEntry(CorporateLawPrototype law, Control container, List<ProtoId<CorporateLawPrototype>> collection, Color? catColor = null)
    {
        var text = law.LawIdentifier != null ? $"{law.LawIdentifier}: {Loc.GetString(law.Title)}" : Loc.GetString(law.Title);
        var control = new SunriseCriminalRecordsLawControl();

        control.Setup(text, collection.Contains(law.ID), _isReadOnly, catColor);

        control.OnToggled += pressed =>
        {
            if (pressed)
            {
                if (!collection.Contains(law.ID))
                    collection.Add(law.ID);
            }
            else
            {
                collection.RemoveAll(id => (string)id == law.ID);
            }
            UpdateSentenceDisplay();
            Save();
        };

        container.AddChild(control);
    }

    private void UpdateSentenceDisplay()
    {
        int total;
        if (_isReadOnly)
        {
            total = _savedSentence;
        }
        else
        {
            // Use shared logic for calculation
            var tempCase = new CriminalCase(_lastCaseId ?? 0, TimeSpan.Zero)
            {
                OriginStation = _ent.GetNetEntity(_ent.System<SharedStationSystem>().GetOwningStation(ConsoleEntity)),
                Laws = _currentLaws,
                Circumstances = _currentCircumstances
            };
            total = _recordsSystem.CalculateSentence(tempCase, _allCases);
        }

        _stationLaw.GetEffectiveLawset(ConsoleEntity, out _, out _, out _, out var threshold);

        if (total >= threshold)
            SentenceLabel.Text = Loc.GetString("sunrise-records-sentence-life");
        else
            SentenceLabel.Text = Loc.GetString("sunrise-records-sentence-total", ("total", total));

        SentenceLabel.FontColorOverride = total >= threshold ? Color.Red : Color.White;
    }

    private Color GetSectionColor(string lawId, List<ProtoId<CorporateLawSectionPrototype>> articles)
    {
        foreach (var sId in articles)
        {
            if (!_proto.TryIndex(sId, out var section) || !section.Entries.Contains(lawId))
                continue;

            return section.Color ?? Color.White;
        }

        return Color.White;
    }

    private Color GetSectionColor(string sectionId)
    {
        if (_proto.TryIndex<CorporateLawSectionPrototype>(sectionId, out var section))
            return section.Color ?? Color.White;

        return Color.White;
    }
}
