using Content.Client.UserInterface.Controls;
using Content.Shared._Sunrise.Shipyard.BUI;
using Content.Shared._Sunrise.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<ProtoId<ShipyardVesselPrototype>>? OnPurchase;
    public event Action? OnSell;

    public ShipyardConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Title = Loc.GetString("shipyard-console-title");
        SellButton.OnPressed += _ => OnSell?.Invoke();
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        if (_prototype.TryIndex(state.Account, out var account))
        {
            AccountLabel.Text = Loc.GetString("shipyard-console-account-name-format",
                ("color", account.Color),
                ("name", Loc.GetString(account.Name)));
        }
        else
        {
            AccountLabel.Text = Loc.GetString("shipyard-console-no-account");
        }

        BalanceLabel.Text = Loc.GetString("shipyard-console-credits-amount", ("amount", state.Balance));
        var currentShuttleName = state.CurrentShuttle is { } currentShuttle &&
            _prototype.TryIndex(currentShuttle, out ShipyardVesselPrototype? currentPrototype)
                ? Loc.GetString(currentPrototype.Name)
                : null;
        CurrentShuttleLabel.Text = currentShuttleName ?? Loc.GetString("shipyard-console-no-shuttle");
        SellValueLabel.Text = currentShuttleName == null
            ? string.Empty
            : Loc.GetString("shipyard-console-sell-value", ("value", state.CurrentShuttleSellValue));
        SellButton.Disabled = currentShuttleName == null || state.TransactionPending;

        Vessels.Children.Clear();
        var vessels = new List<(ShipyardVesselData Data, ShipyardVesselPrototype Prototype, string Name)>();
        foreach (var vesselData in state.Vessels)
        {
            if (!_prototype.TryIndex(vesselData.Id, out var vesselPrototype))
                continue;

            vessels.Add((vesselData, vesselPrototype, Loc.GetString(vesselPrototype.Name)));
        }

        vessels.Sort((left, right) =>
            string.Compare(left.Name, right.Name, StringComparison.CurrentCultureIgnoreCase));

        foreach (var (vessel, vesselPrototype, vesselName) in vessels)
        {
            var vesselDescription = Loc.GetString(vesselPrototype.Description);
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 8,
            };

            row.AddChild(new Label
            {
                Text = vesselName,
                ToolTip = vesselDescription,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            });

            row.AddChild(new Label
            {
                Text = Loc.GetString("shipyard-console-price", ("value", vessel.Price)),
                MinWidth = 105,
                HorizontalAlignment = HAlignment.Right,
                VerticalAlignment = VAlignment.Center,
            });

            var purchase = new Button
            {
                Text = Loc.GetString("shipyard-console-purchase-button"),
                MinWidth = 110,
                Disabled = state.TransactionPending,
                ToolTip = vesselDescription,
            };
            purchase.OnPressed += _ => OnPurchase?.Invoke(vessel.Id);
            row.AddChild(purchase);
            Vessels.AddChild(row);
        }
    }
}
