- type: antag
  id: SELFAgent
  name: roles-antag-selfagent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-selfagent-description
  guides: [ SELFAgent ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24h
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 6h
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 5h
  - !type:RoleTimeRequirement
    role: JobRoboticist
    time: 5h
  playTimeTracker: AntagSELFAgent
  storytellerStress: 0.5

- type: startingGear
  id: SELFAgentGear
  storage:
    back:
    - AccessBreaker
    - EmagFREE
    - SELFStorageImplanter
