- type: gameMapPool
  id: SunriseMapPool
  maps:
  - SunriseDelta
  - SunriseBox
  - SunriseFland
  - SunriseMarathon
  - SunriseBagel
  - SunriseMeta
  - SunrisePlasma
  # Играбельна но требует небольшой доработки
  #- SunriseOasis
  # Неиграбельно
  #- SunriseReach
  # Неиграбельно
  #- SunriseCorvaxGelta
  # SUNRISE-TODO: Старые-новые карты
  #- Glacier
  #- Shoukou
  #- Hammurabi
  #- Lighthouse
  #- Angle
  #- Pebble
  #- Ovni
  #- Kettle
  #- Tortuga
  #- Arena

# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys
