- type: gameMapPool
  id: SunriseMapPool
  maps:
  - SunriseDelta
  - SunriseBox
  - SunriseFland
  - SunriseMarathon
  - SunriseBagel
  - SunriseReach
  - SunriseCorvaxGelta
  - SunriseTrain
  - SunriseMeta
  - SunriseOasis
  - SunriseCog
# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys
