- type: gameMapPool
  id: SunriseMapPool
  maps:
  - SunriseDelta
  - SunriseBox
  - SunriseFland
  - SunriseMarathon
  - SunriseBagel
#  - SunriseReach
#  - SunriseTrain
  - SunriseMeta
# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys
