using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.HelpChoice
{
    [GenerateTypedNameReferences]
    public sealed partial class HelpChoiceWindow : DefaultWindow
    {
        public HelpChoiceWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}

