using Content.Client.UserInterface.Controls;
using Content.Shared._Sunrise.Research.TechnologyDisk;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunrise.Research.TechnologyDisk.UI;

[GenerateTypedNameReferences]
public sealed partial class SunriseDiskConsoleMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action? OnServerButtonPressed;
    public event Action<EntProtoId>? OnPrintButtonPressed;

    private IReadOnlyList<SunriseDiskConsolePrintOption> _diskOptions = [];
    private EntProtoId? _selectedPrototype;
    private int _serverPoints;
    private bool _isPrinting;

    public SunriseDiskConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DiskSelector.OnItemSelected += OnDiskSelected;
        PrintButton.OnPressed += _ =>
        {
            if (_selectedPrototype is { } prototype)
                OnPrintButtonPressed?.Invoke(prototype);
        };
    }

    public void Update(SunriseDiskConsoleBoundUserInterfaceState state)
    {
        TotalLabel.Text = Loc.GetString("tech-disk-ui-total-label", ("amount", state.ServerPoints));
        _diskOptions = state.DiskOptions;
        _serverPoints = state.ServerPoints;
        _isPrinting = state.IsPrinting;

        var previousSelection = _selectedPrototype;
        _selectedPrototype = null;
        DiskSelector.Clear();

        foreach (var option in _diskOptions)
        {
            if (!_prototype.TryIndex<EntityPrototype>(option.Prototype, out var prototype))
                continue;

            var index = DiskSelector.ItemCount;
            DiskSelector.AddItem(prototype.Name, index);
            DiskSelector.SetItemMetadata(index, option.Prototype);

            if (option.Prototype == previousSelection)
            {
                DiskSelector.SelectId(index);
                _selectedPrototype = option.Prototype;
            }
        }

        if (_selectedPrototype == null && DiskSelector.ItemCount > 0)
        {
            DiskSelector.Select(0);
            _selectedPrototype = (EntProtoId) DiskSelector.SelectedMetadata!;
        }

        UpdateCostLabel();
        UpdatePrintButton();
    }

    private void OnDiskSelected(OptionButton.ItemSelectedEventArgs args)
    {
        DiskSelector.SelectId(args.Id);
        _selectedPrototype = (EntProtoId?) DiskSelector.SelectedMetadata;
        UpdateCostLabel();
        UpdatePrintButton();
    }

    private void UpdateCostLabel()
    {
        CostLabel.Text = string.Empty;

        if (_selectedPrototype is not { } selected)
            return;

        foreach (var option in _diskOptions)
        {
            if (option.Prototype != selected)
                continue;

            CostLabel.Text = Loc.GetString("tech-disk-ui-cost-label", ("amount", option.PointCost));
            return;
        }
    }

    private void UpdatePrintButton()
    {
        PrintButton.Disabled = true;

        if (_isPrinting || _selectedPrototype is not { } selected)
            return;

        foreach (var option in _diskOptions)
        {
            if (option.Prototype != selected)
                continue;

            PrintButton.Disabled = _serverPoints < option.PointCost;
            return;
        }
    }
}
