name: CRLF Check

on:
  pull_request:
    types: [ opened, reopened, synchronize, converted_to_draft, ready_for_review ]

# Sunrise added start - отменяем устаревший запуск этой проверки для того же PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
# Sunrise added end

jobs:
  build:
    name: CRLF Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Check for CRLF
      run: Tools/check_crlf.py
