name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Статус: Требует Рассмотрения"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Статус: Ожидает Изменения"
