name: "Labels: Branch staging"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'staging'

jobs:
  add_label:
    if: false # Sunrise-Edit - устаревший сценарий Wizden отключён
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Branch: Staging"
