name: Locale Validator

on:
  push:
    branches: [ staging, trying ]
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.yml'
      - '**.ftl'

jobs:
  validate_ymls:
    name: Validate Locales
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --no-cache-dir PyYAML
      - name: Validate Locales
        run: |
          python3 Tools/_sunrise/Schemas/validate_yml.py Resources/Locale/ Resources/Prototypes/ --ignore Tools/_sunrise/Schemas/ignore_list.yml