name: RGA schema validator
on:
  push:
    branches: [ master, staging, trying ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  yaml-schema-validation:
    name: YAML RGA schema validator
    if: github.actor != 'GitHubActions' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - uses: PaulRitter/yaml-schema-validator@v1
      with:
        schema: Tools/Schemas/rga.yml
        path_pattern: .*attributions.ya?ml$
        validators_path: Tools/Schemas/rga_validators.py
        validators_requirements: Tools/Schemas/rga_requirements.txt
